### ISSUE TITLE
Format Document feature not working

### ISSUE THREAD

**Issue by nitmatgeo** [hashicorp/vscode-terraform#558] opened 2021-02-12 14:35 UTC
I tried all including updating settings.json as below, still no fix. It worked in my other machine. Other colleagues are also facing the issue.
`{
    "terraform.languageServer": {
      "[terraform]": {
        "editor.formatOnSave": true
    },
      "external": true,
      "args": [
        "serve"
      ]
    },   
    "files.autoSave": "afterDelay",
    "terraform-ls.experimentalFeatures": {
    }
  }`

Extension Version: **v2.6.0**

**_Visual Studio Code_**
Version: 1.53.2 (system setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z (1 day ago)
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.16299

**Comment by bradennapier** [comment] 2021-02-19 02:28
Also having this issue and looking at logs it looks like it is trying to access modules that dont exist

```
[2021-02-18 21:25:13.828] [exthost] [error] Error: Cannot find module 'vscode-languageclient'
Require stack:
- /Users/bradennapier/.vscode-insiders/extensions/hashicorp.terraform-2.6.0/out/extension.js
- /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap-fork.js
```

**Comment by sephross** [comment] 2021-03-02 21:27
Also experiencing this issue. Any ETA on a fix? The lack of formatting is a critical issue. Thanks,

**Comment by sidewinder12s** [comment] 2021-03-05 18:19
Just updated to vscode 1.54.1 and installed [terraform-ls version 0.14](https://github.com/hashicorp/terraform-ls/releases/tag/v0.14.0) and format on save appears to be fixed again.

**Comment by nitmatgeo** [comment] 2021-03-06 03:05
Are you able to use the extensions in multiple VS Code windows?

**Comment by sephross** [comment] 2021-03-19 23:52
This still does not work in the latest versions of the language server with an Apple Silicon computer. Choosing to enable the language server and then choosing the format option I receive a toast notification error that there is no formatter available.

**Comment by sephross** [comment] 2021-03-26 01:45
For anyone else having problems running the vscode extension or the language server on apple silicon I was able to work around the format issue by using the latest arm version of the language server via homebrew with

`brew install hashicorp/tap/terraform-ls` 

While the ls does crash fairly consistently it works well enough that I'm able to use the vscode 'Format Document' option on tf files once again.

**Comment by lukesammy** [comment] 2021-07-12 12:59
Getting "there is no formatter for 'terraform' files installed". Downgraded to plugin to version 2.1.1 and it appears to be working again.

**Comment by AndreasFrangopoulos** [comment] 2021-07-14 09:06
Broken on Mac OS version 2.13 with ls 0.19

**Comment by radeksimko** [comment] 2021-07-16 17:52
Closing as a duplicate of https://github.com/hashicorp/vscode-terraform/issues/542

**Closed by radeksimko** 2021-07-16 17:52 UTC
Labels: bug
