### ISSUE TITLE
/* and // incorrectly interpreted as the beginning of a comment in .tf files

### ISSUE THREAD

**Issue by joebenn63** [hashicorp/vscode-terraform#429] opened 2020-07-02 18:28 UTC
The example below from module 5 of [this Pluralsight course](https://app.pluralsight.com/library/courses/getting-started-terraform/table-of-contents) shows /* being interpreted as the beginning of a comment.  In this example the rest of the .tf file is formatted as if it were one long comment.

![image](https://user-images.githubusercontent.com/17015729/86396477-d382de80-bc56-11ea-8d7d-d8c20b1b06a3.png)

**Comment by aeschright** [comment] 2020-07-08 21:49
Hi @joebenn63 -- thanks for reporting this. Could you give us a text snippet for the whole section being highlighted in green? I'll need to see the end of it to know what to fix.

**Comment by joebenn63** [comment] 2020-07-08 23:00
If you look at the resources.tf file in the m5, m6, m7 or m8 folders in the repo below you can see the full files.  The example in the screen shot above is from m5.

https://github.com/ned1313/Getting-Started-Terraform

**Comment by aeschright** [comment] 2020-08-25 22:19
Hi folks, it looks like there was a problem with the heredoc syntax highlighting, but I'm no longer able to reproduce the issue in v2.2.1 so I'm going to close this. Please open a new issue if you see the problem return. Thanks!

**Closed by aeschright** 2020-08-25 22:19 UTC
Labels: bug, syntax
