### ISSUE TITLE
Incorrect diagnostic without default `type = "ssh"` in `connection` block

### ISSUE THREAD

**Issue by woodne** [hashicorp/vscode-terraform#1573] opened 2023-10-04 17:54 UTC
### Extension Version

v2.28.0

### VS Code Version

Version: 1.82.3 (Universal)
Commit: fdb98833154679dbaa7af67a5a29fe19e55c2b73
Date: 2023-10-02T11:06:17.496Z (2 days ago)
Electron: 25.8.1
ElectronBuildId: 24153832
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0

### Operating System

macOS Sonoma 14.0

### Terraform Version

Terraform v1.6.0 on darwin_arm64

### Steps to Reproduce

Create a `.tf` file with the following contents:

```
provider "aws" {
  region = "us-west-2"
}

resource "aws_instance" "test" {
  ami           = "ami-0efcece6bed30fd98"
  instance_type = "m5.large"

  provisioner "remote-exec" {
    connection {
      host = self.private_ip

      port = 22

      bastion_host = "127.0.0.1"
    }

    inline = ["echo 'hello world'"]
  }
}

```

run `terraform init`

run `terraform validate`

### Expected Behavior

`terraform validate` succeeds, and the vscode extension shows no errors

### Actual Behavior

VS code extension is incorrectly reporting that `bastion_host` under the `remote-exec` provisioner `connection` block is unexpected. 

<img width="557" alt="image" src="https://github.com/hashicorp/vscode-terraform/assets/303276/6750a35c-c124-45fc-843f-b64ee9de37c3">

But according to the latest HCL syntax it is indeed correct: https://developer.hashicorp.com/terraform/language/resources/provisioners/connection#argument-reference

### Terraform Configuration

```terraform
provider "aws" {
  region = "us-west-2"
}

resource "aws_instance" "test" {
  ami           = "ami-0efcece6bed30fd98"
  instance_type = "m5.large"

  provisioner "remote-exec" {
    connection {
      host = self.private_ip

      port = 22

      bastion_host = "127.0.0.1"
    }

    inline = ["echo 'hello world'"]
  }
}
```

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by brettcurtis** [comment] 2023-10-04 19:43
This extends out a bit further into tfvars and other places as well.

**Comment by radeksimko** [comment] 2023-10-05 05:49
@woodne Thanks for the report. It looks like [we are missing](https://github.com/hashicorp/terraform-schema/blob/7b256e6c65f9b53047526165ccec7a686b0f3861/internal/schema/0.12/connection_block.go#L14-L81) a number of fields in the `connection` block. The field in question was actually added ages ago in https://github.com/hashicorp/terraform/commit/a7cbbbd25823bca2b4faa2b2786ee7afd6667e60

I'll look into bringing the schema up to date for the block.

@brettcurtis May I ask you to raise a separate issue and attach a snippet of configuration, and ideally a screenshot? Thanks.

**Comment by radeksimko** [comment] 2023-10-05 08:05
Actually it's a little more complicated. I didn't scroll far enough in that file to realise we do in fact track all those fields: https://github.com/hashicorp/terraform-schema/blob/7b256e6c65f9b53047526165ccec7a686b0f3861/internal/schema/0.12/connection_block.go#L126-L131

--- 

## Workaround

There's a relatively straight-forward "workaround" which I'd even call good practice. In other words I would argue this makes configuration better regardless of whether it's flagged by the extension or not.

```hcl
resource "aws_instance" "test" {
  ami           = "ami-0efcece6bed30fd98"
  instance_type = "m5.large"

  provisioner "remote-exec" {
    connection {
      type = "ssh"
      host = self.private_ip
      port = 22
      bastion_host = "127.0.0.1"
    }

    inline = ["echo 'hello world'"]
  }
}
```
^ adding `type = "ssh"` makes it more explicit and obvious to the reader that SSH is in use (rather than "somewhere documented default which happens to be SSH").

--- 

## Fix

I still agree that raising error in the originally reported configuration is confusing/wrong and we should fix that.

Additionally, we are still missing a few other fields anyway for the `ssh` communicator:

![Screenshot 2023-10-05 at 09 04 46](https://github.com/hashicorp/vscode-terraform/assets/287584/48c65744-b362-4baf-9b47-21619167dda2)

I will look into both.

--- 

## Future Feature

We can look into possibly raising _warnings_ or something of that nature for those missing defaults like `type` to encourage best practices. I will file a follow-up issue to track that.

**Comment by radeksimko** [comment] 2023-10-05 11:05
I managed to find solutions for all three issues I described above, and those PRs are now pending review:

 - https://github.com/hashicorp/terraform-schema/pull/270
 - https://github.com/hashicorp/hcl-lang/pull/327
 - https://github.com/hashicorp/terraform-schema/pull/269
 - https://github.com/hashicorp/terraform-schema/pull/268

I will post an update here when we have merged and released this.

**Comment by sheppyj** [comment] 2023-10-05 11:54
My colleagues and I are experiencing the same issue as @brettcurtis where valid tfvars outside of the root of the configuration directory are reporting as incorrect syntax... i've created ;
https://github.com/hashicorp/vscode-terraform/issues/1574

If that is of any help @radeksimko

**Comment by brettcurtis** [comment] 2023-10-05 13:25
Another example with `terraform_remote_state` datasource if it's helpful:

![image](https://github.com/hashicorp/vscode-terraform/assets/1610100/e124feae-c927-45dc-90ea-2dc481aa8897)

**Comment by kkirpichnikov** [comment] 2023-10-05 14:38
One more example from a `.hcl` file that is used for `terragrunt`
![image](https://github.com/hashicorp/vscode-terraform/assets/13055750/cd792f8b-46b4-4fb0-b38a-4fc3a352f3dd)

**Comment by radeksimko** [comment] 2023-10-05 15:04
@kkirpichnikov We do not support non-Terraform HCL files and we never did (at least since v2). The Terraform extension intentionally avoids claiming `*.hcl` as it cannot provide any value to arbitrary HCL files - as demonstrated by the diagnostics on the screenshot. If you configured VS Code such that it treats all `*.hcl` as Terraform then I'd suggest to remove that settings.

There is [HCL extension](https://marketplace.visualstudio.com/items?itemName=HashiCorp.HCL) which can help with syntax highlighting which you can install and it shouldn't need any additional tweaking as it automatically claims `*.hcl` and that will work for Terragrunt and other HCL-based languages, like Packer, Nomad etc.

--- 

For anyone else experiencing incorrect diagnostics that aren't the same as in the initial post I would kindly ask you to create new issue and attach a screenshot and code to copy paste to help us reproduce.

**Comment by kkirpichnikov** [comment] 2023-10-05 15:14
@radeksimko anyway, it was working for a very long time till the latest release.

**Comment by voxmaster** [comment] 2023-10-05 15:58
.tfvars looks also broken

<img width="774" alt="image" src="https://github.com/hashicorp/vscode-terraform/assets/23716907/73bb0101-c46c-44e8-bd4f-a8b4f77f48d8">

**Comment by radeksimko** [comment] 2023-10-05 16:00
For anyone else experiencing incorrect diagnostics that aren't the same as in the initial post I would kindly ask you to create new issue and attach a screenshot and code to copy paste to help us reproduce instead of attaching more comments here.

Thanks!

**Comment by radeksimko** [comment] 2023-10-06 14:12
A new version [2.28.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.28.1) was just released. This fixes all the three mentioned bugs in my comment above, including the originally reported bug by @woodne. The update should appear automatically in VS Code.

Thank you for the timing and level of detail in your report @woodne

--- 

In case you experience any different validation related bug, please do let us know through a new issue.

**Closed by radeksimko** 2023-10-06 14:12 UTC
Labels: bug, diagnostics
