### ISSUE TITLE
No declaration found for nested object in list

### ISSUE THREAD

**Issue by jonasbbernardi** [hashicorp/vscode-terraform#1694] opened 2024-02-16 05:02 UTC
### Extension Version

v2.29.4

### VS Code Version

![image](https://github.com/hashicorp/vscode-terraform/assets/14101440/02245f43-ee54-44b5-8c82-5f86b5cb6ff9)

### Operating System

Windows 11 Pro

### Terraform Version

terraform v1.7.1

### Steps to Reproduce

1. create local variable:
```terraform
locals {
  apps = [{}]
}
```
2. In a resource, using the local variable in for, inside a for_each. Ex:
![image](https://github.com/hashicorp/vscode-terraform/assets/14101440/34aac43a-4103-4956-99b1-ba2199593b4c)

### Expected Behavior

To not show error

### Actual Behavior

Setting variable usage as error *"No declaration found for local.<...>"*

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by scott-doyland-burrows** [comment] 2024-02-16 07:54
I'd say this is the same issue as https://github.com/hashicorp/vscode-terraform/issues/1693

**Comment by dbanck** [comment] 2024-02-16 09:15
Closing this as a duplicate of #1693, as @scott-doyland-burrows helpfully pointed out.

You can also find [a workaround in my comment](https://github.com/hashicorp/vscode-terraform/issues/1693#issuecomment-1943326443) over there.

**Closed by dbanck** 2024-02-16 09:15 UTC
Labels: bug
