### ISSUE TITLE
All values in tfvars are detected as attribute not expected here

### ISSUE THREAD

**Issue by deniscooper** [hashicorp/vscode-terraform#1600] opened 2023-10-18 12:17 UTC
### Extension Version

v2.28.2

### VS Code Version

Version: 1.83.0
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:13:10.518Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0

### Operating System

Mac OS Sonoma 14.0

### Terraform Version

Terraform v1.6.1 on darwin_arm64

### Steps to Reproduce

1. Create a new folder
2. Create a file called variables.tf
3. Create a variable block variable  

`variable "disposition" {
  type = string
}`

4. create a file in the folder called values.tfvars
5. create a line in the file disposition = ""

vs code TF extension reports disposition attribute is not expected here

This has happened since after version 2.27.2 - it works okay in 2.27.2

### Expected Behavior

It should not detect an invalid attribute in tfvars file

### Actual Behavior

Error is detected, lines underlined in red error, vscode reports attribute not expected here

### Workarounds

Downgrade extension to 2.27.2

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by deniscooper** [comment] 2023-10-18 12:23
if the tfvars file is named terraform.tfvars the issue doesn't happen

**Comment by radeksimko** [comment] 2023-10-19 10:15
Hi @deniscooper 
I was not able to reproduce this by following the steps you provided. See attached screen recording below.


https://github.com/hashicorp/vscode-terraform/assets/287584/abc514f8-1761-4b2e-b966-e2d475792fb2

To help us get to the bottom of the issue:

1. Can you double check the language server version in the bottom bar, like I did in the recording?
2. If the LS version does not match `0.32.2`, can you check and remove any custom settings such as `terraform.languageServer.path`?
3. Can you double check the language ID in the same bottom bar says `terraform-vars` for the `*.tfvars` file (i.e. _not_ `terraform`) and similarly it says `terraform` for the `*.tf` files?
4. If you have any custom associations for the filetypes affecting (3), can you remove these?
5. Failing all of the above, can you provide us with the [full log](https://github.com/hashicorp/terraform-ls/blob/main/docs/TROUBLESHOOTING.md#logging) to inspect?

**Comment by deniscooper** [comment] 2023-10-19 19:47
looks like the issue might have been a missing file association, it wasn't detecting tfvars files

thanks for checking and the support

**Comment by radeksimko** [comment] 2023-10-24 10:32
> looks like the issue might have been a missing file association, it wasn't detecting tfvars files

To clarify - the extension provides automatic association. There is no need to be _adding_ anything to settings. I was therefore implying that if you _have_ added a manual association for anything Terraform related (`*.tf` or `*.tfvars`) then this may be the reason for something not working as it should.

The extension should generally work fine "out of the box" (without additional settings) when it comes to file association.

I'm going to close this issue since this was presumably a settings issue, as confirmed.

--- 

@guipaivanz you are free to [open a new issue](https://github.com/hashicorp/vscode-terraform/issues/new/choose) and attach a repro case + ideally follow the steps I outlined above.

**Closed by radeksimko** 2023-10-24 10:32 UTC
Labels: question, waiting-response
