### ISSUE TITLE
hashicorp.terraform 2.9.0 failed to install with "ENOENT: no such file or directory" error.

### ISSUE THREAD

**Issue by GrooveGod** [hashicorp/vscode-terraform#597] opened 2021-03-24 19:27 UTC
I'm getting this output in _Log (shared)_ in VSCode (version: 1.54.3) when v2.9.0 tries to install.  The error is reproducible using the [Update to 2.9.0] button in the Extensions panel. I have not attempted the VSIX installer.  I tried creating the extension folder manually just to see if the install could get any further to no avail.  

Any suggestions?

```txt
[2021-03-24 12:10:10.504] [sharedprocess] [info] Installing extension: hashicorp.terraform
[2021-03-24 12:10:10.620] [sharedprocess] [info] Downloaded extension: hashicorp.terraform undefined
[2021-03-24 12:10:10.656] [sharedprocess] [error] Failed to install extension: hashicorp.terraform ENOENT: no such file or directory, mkdir 'c:\Users\{username}\.vscode\extensions\.hashicorp.terraform-2.9.0\file:\Users\aeschright\code\vscode-terraform\lsp'
[2021-03-24 12:10:10.657] [sharedprocess] [error] [uncaught exception in sharedProcess]: ENOENT: no such file or directory, mkdir 'c:\Users\{username}\.vscode\extensions\.hashicorp.terraform-2.9.0\file:\Users\aeschright\code\vscode-terraform\lsp': extracting: ENOENT: no such file or directory, mkdir 'c:\Users\{username}\.vscode\extensions\.hashicorp.terraform-2.9.0\file:\Users\aeschright\code\vscode-terraform\lsp'
    at h.extractAtLocation (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:198822)
    at async h.extractUserExtension (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:196834)
    at async G.extractAndInstall (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:212922)
    at async G.doInstallFromGallery (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:209430)
```

**Comment by KyL0R3Nz0** [comment] 2021-03-24 19:30
The suggestion is that whoever built this VSIX file hard-coded the path to their own user profile into the distribution:

ENOENT: no such file or directory, mkdir 'c:\Users\_<user_dir>_\.vscode\extensions\.hashicorp.terraform-2.9.0\file:\Users\**_aeschright_**\code\vscode-terraform\lsp'

I'm sure that **_AESCHRIGHT_** will fix this, if this is indeed the problem.

**Comment by killyosaur** [comment] 2021-03-24 19:41
probably should check issues when an error like this pops up :P https://github.com/hashicorp/vscode-terraform/issues/596

**Comment by aeschright** [comment] 2021-03-24 20:12
Closing as a duplicate of #596 -- please comment over there 👍

**Closed by aeschright** 2021-03-24 20:12 UTC

**Comment by GrooveGod** [comment] 2021-03-24 20:14
#596 didn't exist when I was entering this one... I did check.  We must have been entering them near the same time.
