### ISSUE TITLE
Make the VSCode extension compatible with https://vscode.dev/ and https://github.dev/

### ISSUE THREAD

**Issue by codecycleteam** [hashicorp/vscode-terraform#1071] opened 2022-04-25 06:03 UTC
## Versions

This feature does not yet exist in:
 - [x] the **latest** version of the extension (below)
 - [x] the **latest** version of the language server (below)

### Extension

```

```

### Language Server

```

```

## Problem Statement

Developers are not able to use this extension with https://vscode.dev/ and https://github.dev/

## Proposal

Make the VSCode extension compatible with https://vscode.dev/ and https://github.dev/
@allevato @thomasvl @dierksen @reinhillmann @philwo @fweikert
Please consider this as DX improvement and give some priority for it.
Thanks

## References

Here is more info
https://aka.ms/vscode-web-extensions-guide
https://code.visualstudio.com/api/extension-guides/web-extensions

Screenshot of extension showing not compatible with web version.
![Screenshot 2022-04-25 11 24 03](https://user-images.githubusercontent.com/84431724/165029500-d76b6490-304b-402f-bd2f-f5a3a54adca3.png)

**Comment by radeksimko** [comment] 2022-04-25 06:59
Closing this as a duplicate of https://github.com/hashicorp/vscode-terraform/issues/768

**Closed by radeksimko** 2022-04-25 06:59 UTC
Labels: enhancement
