### ISSUE TITLE
[Feature Request] Support for AzureRM provider autocomplete

### ISSUE THREAD

**Issue by IanMoroney** [hashicorp/vscode-terraform#511] opened 2020-11-12 11:22 UTC
Language server doesn't seem to understand provider contexts at all for autocomplete. I.E. Azurerm:

![azurerm](https://user-images.githubusercontent.com/10791260/98934012-59524880-24d9-11eb-8900-4e47fd7f68ef.gif)

**Comment by IanMoroney** [comment] 2020-11-12 11:25
Incidentally, i think this is a duplicate of #373 but clearly shows the problem mentioned.

**Comment by radeksimko** [comment] 2020-11-12 12:59
Yes, I believe this is a duplicate of #373 - thank you for the report, I will close this one to keep discussion in one place.

**Closed by radeksimko** 2020-11-12 12:59 UTC
