### ISSUE TITLE
Terraform Auto Complete not working

### ISSUE THREAD

**Issue by kmayer10** [hashicorp/vscode-terraform#689] opened 2021-07-15 15:23 UTC
Issue Type: <b>Bug</b>

I have installed the Terraform Extension in my VS Code but I am not able to get the auto complete option for the same and still I have to write entire code by myself.

Extension version: 2.13.0
VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (6.00GB free)|
|Process Argv|--crash-reporter-id 0ebc3d92-344d-455e-ae98-81c9086a325d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
bridge0708:30335490

```

</details>

**Comment by radeksimko** [comment] 2021-07-16 08:14
Hi @kmayer10 
As mentioned in other issues there is some likelihood this was caused by the bug which was fixed in #688

I just released that bug fix as part of v2.13.1. Can you try upgrading to that version and confirm it resolved the mentioned issues? If not I am happy to reopen and investigate. Thanks.

**Closed by radeksimko** 2021-07-16 08:14 UTC
