### ISSUE TITLE
Format-on-Save Stopped Working?

### ISSUE THREAD

**Issue by david-abarca** [hashicorp/vscode-terraform#687] opened 2021-07-15 10:54 UTC
Hi,

Recently my format-on-save stopped working and I've checked the docs however nothing new that I can see that I need to adjust in case of an update.

Here's my tf-related config.

```
"[terraform]": {
  "editor.formatOnSave": true,
  "editor.tabSize": 4,
},
```

VSCode TF Version: v2.13.0

Anyone else having these issues or might know what I can adjust?

**Comment by politician** [comment] 2021-07-16 03:28
Yes I have the same issue!

**Comment by politician** [comment] 2021-07-16 03:41
Actually after running more tests, I realize that even formatting won't work if you "Add a folder to workspace" in VS Code. So in my case it was a duplicate of https://github.com/hashicorp/vscode-terraform/issues/685

**Comment by radeksimko** [comment] 2021-07-16 08:13
As @politician mentioned there is some likelihood this was caused by the bug which was fixed in #688 

I just released that bug fix as part of `v2.13.1`. Can you try upgrading to that version and confirm it resolved the mentioned issues? If not I am happy to reopen and investigate. Thanks.

**Closed by radeksimko** 2021-07-16 08:13 UTC

**Comment by david-abarca** [comment] 2021-07-16 08:59
Cheers, glad to hear a fix is on its way on the case you pointed to! :)

**Comment by radeksimko** [comment] 2021-07-16 09:03
That new release should already be available in VS Code Marketplace (you may need to restart VS Code for it to show) - let me know if that resolved the issues.

![Screenshot 2021-07-16 at 10 03 35](https://user-images.githubusercontent.com/287584/125922656-d53cce3a-ed31-4a09-8a08-d91c4fef39ac.png)

**Comment by david-abarca** [comment] 2021-07-16 09:12
Yeah, I just updated and it works like a charm! :)

I did however had to force it since for some reason another extension (prettier) was taking over.

```
"[terraform]": {
  "editor.defaultFormatter": "hashicorp.terraform",
  "editor.formatOnSave": true,
  "editor.tabSize": 2,
},
```

**Comment by radeksimko** [comment] 2021-07-16 17:37
Thank you for that extra context @david-abarca - this is helpful!

Unfortunately it's not the first time that I see a weird bug being caused by conflicts between multiple extensions claiming `terraform` language. I raised https://github.com/hashicorp/vscode-terraform/pull/693 and also created https://github.com/hashicorp/vscode-terraform/issues/692

btw. that third line (`tabSize`) you have there has no effect because Terraform itself (`terraform fmt`) is quite opinionated in how it does formatting and doesn't allow for indentation style to be any different than prescribed (two spaces).
