### ISSUE TITLE
Toggle Comment not working

### ISSUE THREAD

**Issue by nexxai** [hashicorp/vscode-terraform#502] opened 2020-10-19 16:16 UTC
I'm not sure what happened but the Toggle Comment keyboard shortcut does not seem to be working.  I've confirmed that it's limited to this particular plugin by uninstalling it and reinstalling it and it not working, while trying other Terraform plugins and them working correctly.  I've also tried physically deleting the entire plugin folder from ~/.vscode/extensions folder to ensure that there weren't any stragglers from old versions, and I've also made sure that there were no plugin-specific settings in the settings.json being set.

Has anyone seen this before?

**Comment by nexxai** [comment] 2020-11-20 17:44
Update: sometimes completely deleting the `hashicorp-terraform-<ver>` folder from `~/.vscode/extensions` does the trick for a while, but then it stops working again after some random number of days.

**Comment by JeremieBethmont** [comment] 2020-12-03 01:14
I confirm the above. In order to re-enable toggle comments on TF file I had to do both:
- delete: `~/.vscode/extensions/hashicorp-terraform-<ver>` 
- reinstall the plugin

**Comment by aeschright** [comment] 2020-12-16 19:23
Sorry you're seeing that behavior! Can you tell us what version you have for VSCode and the extension?

**Comment by nexxai** [comment] 2020-12-16 20:02
`hashicorp.terraform-2.3.0`

**Comment by alex-malone** [comment] 2021-02-10 16:27
Happening to me as well, VSCode v1.53.0,  Hashicorp Terraform 2.6.0.

Comment toggle works fine with other files I've tried (py, md, tpl), just doesn't work with .tf/.tfvars files since I updated to 2.6.0.

**Comment by nexxai** [comment] 2021-04-13 22:42
Prior to today, I could remove/re-add when it crashed, but I'm not sure what happened but since the update to VSCode March 2021 and version 2.10.0 of the extension, even removing and re-adding doesn't work any more.

**Comment by aeschright** [comment] 2021-04-13 22:58
Just to make sure we're looking at all the possibilities: what platform are you running VSCode on? and do you have anything like `editor.autoClosingQuotes` or `editor.autoClosingBrackets` in your settings?

Also, does this issue still happen if you disable the language server? ("Terraform: Disable Language Server" in the command palette)

**Comment by nexxai** [comment] 2021-04-14 00:28
In order:
1. OS: macOS Big Sur 11.2.3
2. Those settings don't exist in my settings
3. Disabling the language server does seem to solve the problem, but then after re-enabling it, the issue stays resolved; I'm not sure what disabling and re-enabling it did but it would appear that the act of doing so resets something else?

**Comment by sketabchi-mobiz** [comment] 2021-05-08 15:23
I noticed this is not just a shortcut issue or keybinding; The toggle block or line comment does not work even from the `Edit` menu option.

**Comment by nexxai** [comment] 2021-05-18 14:35
Also another update: disabling the language server and re-enabling it used to work but now with one of the most recent updates, it no longer does.  I have to go manually remove the full Terraform extension folder from `~/.vscode/extensions` and then reinstall it.

**Comment by akr257** [comment] 2021-07-13 00:33
I'm experiencing the same issue. I have tried the following steps and none of them have worked:

1. Uninstall and reinstall 2.13.0 of the extension
2. Downgrade to an older version of the extension
3. Deleting the extensions folder and installing it again 

Version: 1.58.0
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:17.694Z (4 days ago)
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 18.7.0

**Comment by dsmithbauer** [comment] 2021-07-27 12:25
> 3. Disabling the language server does seem to solve the problem, but then after re-enabling it, the issue stays resolved; I'm not sure what disabling and re-enabling it did but it would appear that the act of doing so resets something else?

After weeks of being frustrated with this and trying the deletion and reinstallation of the extension to no avail, disabling and reenabling the language server worked for me as well! Thanks!

HashiCorp Terraform extension v2.14.0

Version: 1.58.0 (Universal)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:17.694Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.6.0

**Comment by radeksimko** [comment] 2021-07-27 13:03
I'm going to close this as a duplicate of https://github.com/hashicorp/vscode-terraform/issues/480 just to keep any relevant discussion in one place.

**Closed by radeksimko** 2021-07-27 13:03 UTC
Labels: bug
