### ISSUE TITLE
Format on save does not work

### ISSUE THREAD

**Issue by audiolomb** [hashicorp/vscode-terraform#1265] opened 2022-11-03 15:08 UTC
Issue Description
=====

Format on Save does not work

Environment Information
=====

Terraform Information
-----

Version:	1.2.5
Platform:	windows_amd64
Outdated:	true
    

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.17763 |
| VSCode | 1.73.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|isort|ms-python|2022.4.0|
|powershell|ms-vscode|2022.10.0|
|python|ms-python|2022.18.0|
|remote-containers|ms-vscode-remote|0.262.3|
|remote-ssh|ms-vscode-remote|0.90.1|
|remote-ssh-edit|ms-vscode-remote|0.84.0|
|remote-wsl|ms-vscode-remote|0.72.0|
|svn-scm|johnstoncode|2.15.5|
|terraform|hashicorp|2.24.3|
|vscode-remote-extensionpack|ms-vscode-remote|0.21.0|
|vscode-yaml|redhat|1.10.1|
</details>

Extension Logs
-----

> Find this from the first few lines of the relevant Output pane:
View -> Output -> 'HashiCorp Terraform'

**Comment by dbanck** [comment] 2022-11-03 17:06
Hi @audiolomb!

Sorry to hear that format on saving isn't working for you. Do you mind sharing your VS Code settings and the extension logs, so we can better identify the issue. Thanks!

**Comment by cschar** [comment] 2022-11-04 17:10
same for me, looked into extension logs and saw

```
[2022-11-04 13:07:36.580] [exthost] [error] Error: fmt was first introduced in Terraform 0.7.7: unable to parse version "": Malformed version: 
    at je (/Users/cody/.vscode/extensions/hashicorp.terraform-2.24.2-darwin-arm64/out/extension.js:17:223)
    at Ue (/Users/cody/.vscode/extensions/hashicorp.terraform-2.24.2-darwin-arm64/out/extension.js:16:11251)
    at Immediate.<anonymous> (/Users/cody/.vscode/extensions/hashicorp.terraform-2.24.2-darwin-arm64/out/extension.js:16:11101)
    at processImmediate (node:internal/timers:466:21)
```

**Comment by dbanck** [comment] 2022-11-07 09:00
> same for me, looked into extension logs and saw

Which Terraform version are you using? Unfortunately, the language server cannot determine the version and cannot offer formatting support without knowing it.

**Comment by dawsonar802** [comment] 2022-11-07 12:05
Hello, I am experiencing the same issues with format on save.  It will essentially hang and not complete.  I am using a devcontainer as well.  I have updated to TF version `1.3.4` and vscode version `1.73.0`.  I have attached a screenshot of the log file, which essentially this message is just repeated a few times each time I try to save.  All I did was go into a working main.tf file, add some text at the bottom of the file, then remove it and save the file.  Vscode tells me there are problems in the file, then the formatting hangs.  

![Screenshot 2022-11-07 070103](https://user-images.githubusercontent.com/62777308/200305882-4cd8d9d8-c5c9-462c-af08-f10f5922cfab.png)

**Comment by rd-michel** [comment] 2022-11-08 13:41
same problem here:
vscode: 1.73.00
Terraform v1.3.4
vscode extension version: v2.24.3

**Comment by radeksimko** [comment] 2022-11-15 08:29
I unfortunately cannot confirm that the root cause is the same for everyone - even if the problem is surfaced as "formatting doesn't work".

@cschar Thank you for sharing the relevant part of the log. Building on that - Can you run `which terraform` in the same directory and environment? Is it possible that you use tfenv or another kind of wrapper around terraform, or version manager of some kind? Can you try running `terraform version`? What I'm guessing the problem may be is that the wrapper prints some errors (such as "terraform version x.y.z not installed") into stderr, and we attempt to parse the stdout for version, which is empty.

--- 

@dawsonar802 @audiolomb @rd-michel Can each of you look into the `HashiCorp Terraform` log pane and find & share any parts of it between `request for "textDocument/formatting"` and `Response to "textDocument/formatting"`? Alternatively sharing the whole log would help - we can look it up.

![Screenshot 2022-11-15 at 08 24 20](https://user-images.githubusercontent.com/287584/201867632-c7faa0c6-6f01-443c-82ab-510e8fc9f53f.png)

**Comment by dawsonar802** [comment] 2022-11-15 12:17
@radeksimko , I updated the extension to v2.25.0 and reproduced the issues.  Below is a screenshot if it helps at all with the behavior.  I made a change, saved the file, and then this window will come up for several seconds/minutes.  
![Screenshot 2022-11-15 071002](https://user-images.githubusercontent.com/62777308/201916991-6020649d-fa62-4b87-b4fa-5351a1d403b6.png)

Is there another may I can send/share the log with you vs posting it here?  The log file is pretty large and has a lot to be redacted it looks like.  If not, here is another screenshot which has the /formatting section:
![Screenshot 2022-11-15 071425](https://user-images.githubusercontent.com/62777308/201917471-8ecc550a-aadb-4743-92f3-e327725cf77c.png)

To add a bit of content, in our case anyway, we have a root module that is calling other modules.  The root module is local and the other modules are hosted in a private registry.

**Comment by radeksimko** [comment] 2022-11-15 12:30
@dawsonar802 Thank you for sharing the log. According to that, it appears you're likely affected by https://github.com/hashicorp/terraform-ls/issues/1063 where LSP requests (including the formatting ones) are delayed due to slow external network requests.

Can you try commenting out any/all module calls and reproduce it? Relatedly - _if_ you can share any details about the modules sources involved, that would be helpful! It appears that the metadata for those aren't available on the public registry (according to the log with 404s) - which would confirm your theory above. That said, responding with 404s should be relatively fast still. I guess the issue with blocking may still come up when there's _many_ module calls, i.e. many HTTP requests to send and process. The API unfortunately doesn't have any kind of batching functionality, but we should of course prevent it from blocking other LSP requests.

> Is there another may I can send/share the log with you vs posting it here?

Feel free to send it to `radek <at> hashicorp.com` and/or encrypt it using my PGP key: https://keybase.io/radeksimko

**Comment by KTamas** [comment] 2023-01-04 14:23
Format on save continues to be basically useless for me, it can take 10-20 seconds to save a file on a reasonable network connection. 
<img width="374" alt="Screenshot 2023-01-04 at 14 05 33" src="https://user-images.githubusercontent.com/48946/210575835-6eb79332-8bd9-468d-bb83-08380bbf1432.png">

**Comment by dawsonar802** [comment] 2023-02-04 03:26
To my knowledge this has not been fixed.  I will try and confirm next week, but have just been using an earlier version of the extension until there was an update here.

**Comment by KTamas** [comment] 2023-02-04 12:25
@dawsonar802 which is the last good version?

**Comment by dawsonar802** [comment] 2023-02-04 12:31
I have been using 2.22, but 2.24.2 works as well from another post here.

**Comment by dawsonar802** [comment] 2023-02-09 14:47
I was on version `2.24.2` and facing the issues.  I upgraded to the latest `2.52.2` and still had the issues.  I have reverted back to `2.22.0` and do not have the issues currently.  Have there been any updates on what may be causing this issue?  From what I can tell this seems to mainly happen when using modules, specifically with the source being something other than local.  For example, I am working on a new common module and have it currently local vs being in a registry.  I can save it fine, auto complete works fine, and no hangs on format when using the newer versions mentioned above.

**Comment by albertorm95** [comment] 2023-02-27 12:11
` <= v2.23.0` Works for me

**Comment by philipsparrow** [comment] 2023-03-02 03:15
I've been having the same issue. brew installed tfenv, tried installing terraform-ls using Brew and pointing the extension to that binary, but I was getting this same error about the malformed version `""`.
Downgrading to v2.23.0 worked for me.

**Comment by KTamas** [comment] 2023-03-02 11:41
Thanks everyone, downgraded to v2.23.0 and so far so good.

**Comment by evbo** [comment] 2023-03-17 19:47
version v.2.23.0 does not work for me inside a .devcontainer. Here is my settings, any suggestions?:

```json
{
    "workbench.colorTheme": "Default Dark+",
    "security.workspace.trust.untrustedFiles": "open",
    "files.watcherExclude": {
        "**/.bloop": true,
        "**/.metals": true,
        "**/.ammonite": true
    },
    "files.autoSave": "afterDelay",
    "editor.mouseWheelZoom": true,
    "editor.minimap.enabled": false,
    "terminal.integrated.scrollback": 100000,
    "window.zoomLevel": 3,
    "terminal.integrated.profiles.linux": {
        "bash": {
            "path": "/bin/bash"
        }
    },
    "terminal.integrated.defaultProfile.linux": "bash",
    "terraform.experimentalFeatures.validateOnSave": true,
    "terraform.experimentalFeatures.prefillRequiredFields": true,
    "[terraform]": {
        "editor.defaultFormatter": "hashicorp.terraform",
        "editor.formatOnSave": true,
        "editor.formatOnSaveMode": "file"
    },
    "[terraform-vars]": {
        "editor.defaultFormatter": "hashicorp.terraform",
        "editor.formatOnSave": true,
        "editor.formatOnSaveMode": "file"
    }
}
```

**Comment by ThePlenkov** [comment] 2023-04-07 16:10
I've spent quite some time to come here. Any updates on this topic?

**Comment by albertorm95** [comment] 2023-05-02 08:53
Any of you using `<=0.23.0` facing the 
https://support.hashicorp.com/hc/en-us/articles/13177506317203

**Comment by radeksimko** [comment] 2023-05-02 09:04
@albertorm95 This sounds like a separate topic, but in general I'd suggest upgrading to the latest version to address that. If you experience issues with that version, we can discuss those issues and get to the bottom of it.

As for the original issue in the first post - We have made some improvements wrt performance in the latest version [2.26.0](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.26.0) as per https://github.com/hashicorp/terraform-ls/pull/1258 We plan to make some more changes 🔜 as part of https://github.com/hashicorp/terraform-ls/issues/1056 to help address other similar situations.

There were other root causes discussed here, including missing Terraform CLI or use of wrappers or 3rd party package managers such as tfenv. We'd be happy to discuss those in a separate issue if anyone can provide details about their situation and environment.

With that in mind, I'll close this issue as the _initial_ issue (involving inaccessible Registry modules delaying formatting) was addressed.

**Closed by radeksimko** 2023-05-02 09:04 UTC
Labels: bug, waiting-response
