### ISSUE TITLE
Setting contribution error on activation

### ISSUE THREAD

**Issue by joaomoreno** [hashicorp/vscode-terraform#1182] opened 2022-07-17 05:36 UTC
### Extension

```
2.23.0
```

### VS Code

```
1.70.0-insider
```

### Operating System

```
Windows 11
```

### Steps To Reproduce

1. Install the extension
2. Open DevTools in the workbench

### Expected Behavior

No errors.

### Actual Behavior

A bunch of errors:

![image](https://user-images.githubusercontent.com/22350/179385333-5d8fd993-65c0-4c1c-85b3-1424eb29df49.png)
 
### Additional context

Very likely related to https://github.com/hashicorp/vscode-terraform/issues/791

**Comment by jpogran** [comment] 2022-07-18 14:10
Hi @joaomoreno thanks for reporting this. This is fixed by, not caused by, #791.

 We added `terraform.languageServer.ignoreSingleFileWarning` in https://github.com/hashicorp/vscode-terraform/pull/1031, but did not extract `terraform.languageServer` until https://github.com/hashicorp/vscode-terraform/pull/1156.

We have a release scheduled soon to ship https://github.com/hashicorp/vscode-terraform/pull/1156 with a migration UX that will help remove this error from the extension host logs.

**Comment by mjnorman** [comment] 2022-07-27 16:04
@jpogran Will this also address the gui error with the similar message?

![image](https://user-images.githubusercontent.com/21270587/181295258-716c1f63-7f70-4334-9a42-4e9d91d61298.png)

**Comment by jpogran** [comment] 2022-07-27 23:34
Yep!

**Comment by jpogran** [comment] 2022-08-23 15:04
Version 2.24.0 has been released, which includes all the changes necessary to remove any errors in the extensionhost logs and with the latest terraform-ls release to remove the warning about unknown configuration options.

**Closed by jpogran** 2022-08-23 15:04 UTC
Labels: bug
