### ISSUE TITLE
Syntax highlighting of indented heredoc is incorrect

### ISSUE THREAD

**Issue by haxorof** [hashicorp/vscode-terraform#197] opened 2019-07-05 12:39 UTC
Heredoc like (<<EOF) is correctly highlighted but if you are using indented heredoc (<<-EOF) the it is not highlighting that correctly. The regexp here is the problem: 
https://github.com/mauve/vscode-terraform/blob/master/syntaxes/terraform.json#L283

This could for example be changed to:
```
"begin": "(?>\\s*<<[\\s\\-]?(\\w+))",
```

Example in Terraform documentation can be found here: https://www.terraform.io/docs/configuration/expressions.html

**Comment by jpogran** [comment] 2022-01-31 14:25
Hi @haxorof, 

I've been working through the `syntax` type tickets and in reviewing this ticket I can't reproduce the incorrect highlighting. I tried a couple of different variations and highlighting works in all cases I could think of.

![image](https://user-images.githubusercontent.com/272569/151810865-f6fd425b-29fb-4c19-993d-220d1c8340d6.png)

Can you reply with an example where it breaks?

**Comment by jpogran** [comment] 2022-02-01 16:39
After consulting https://www.terraform.io/language/expressions/strings#indented-heredocs and comparing to latest extension output, I think we resolved this problem at some point in the past and did not circle back on this ticket.

I'm going to close this now, but if this is still an issue for you, please don't hesitate to let us know.

**Closed by jpogran** 2022-02-01 16:39 UTC
Labels: syntax, waiting-response
