### ISSUE TITLE
Does not format file after save anymore :-/

### ISSUE THREAD

**Issue by KhimairaCrypto** [hashicorp/vscode-terraform#879] opened 2021-12-25 22:45 UTC
Issue Description
=====

autocompleation does not work, unable to autoformat file even after configuration added to vs code configuration file

```
 "[terraform]": {
    "editor.defaultFormatter": "hashicorp.terraform",
    "editor.formatOnSave": true
  }
```

I installed and uninstalled terraform-ls and no change. I enable/disabled Language Server and VS code and no change :-/

Environment Information
=====

Terraform Information
-----

Version:	Not found
Platform:	Not found
Outdated:	false
    

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Darwin arm64 21.2.0 |
| VSCode | 1.63.2|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|auto-close-tag|formulahendry|0.5.13|
|auto-rename-tag|formulahendry|0.1.9|
|autoimport|steoates|1.5.4|
|Bookmarks|alefragnani|13.2.2|
|code-spell-checker|streetsidesoftware|2.0.14|
|Cyberpunk|max-SS|1.2.14|
|dart-code|Dart-Code|3.29.0|
|docker-explorer|formulahendry|0.1.7|
|dotenv|mikestead|1.0.1|
|EditorConfig|EditorConfig|0.16.4|
|es7-react-js-snippets|dsznajder|3.1.1|
|fig|withfig|0.0.5|
|file-icons|file-icons|1.0.29|
|flutter|Dart-Code|3.29.0|
|gc-excelviewer|GrapeCity|4.0.45|
|gitlens|eamodio|11.7.0|
|headwind|heybourn|1.7.0|
|highlight-matching-tag|vincaslt|0.10.1|
|indent-rainbow|oderwat|8.2.2|
|LiveServer|ritwickdey|5.6.1|
|markdown-all-in-one|yzhang|3.4.0|
|material-icon-theme|PKief|4.11.0|
|mdx|silvenon|0.1.0|
|mongodb-vscode|mongodb|0.7.0|
|nextjs|WillLuke|0.0.8|
|numbered-bookmarks|alefragnani|8.1.0|
|prettier-vscode|esbenp|9.0.0|
|quicktype|quicktype|12.0.46|
|quokka-vscode|WallabyJs|1.0.435|
|rest-client|humao|0.24.6|
|scala|scala-lang|0.5.5|
|seti-icons|qinjia|0.1.3|
|shades-of-purple|ahmadawais|6.13.0|
|solidity|JuanBlanco|0.0.136|
|tailwind-docs|austenc|1.4.0|
|terraform|hashicorp|2.17.0|
|theme-dracula-pro|dracula-theme-pro|1.1.0|
|vsc-material-theme-icons|equinusocio|2.2.1|
|vscode-codemetrics|kisstkondoros|1.24.0|
|vscode-docker|ms-azuretools|1.18.0|
|vscode-eslint|dbaeumer|2.2.2|
|vscode-graphql|GraphQL|0.3.41|
|vscode-great-icons|emmanuelbeziat|2.1.79|
|vscode-icons|vscode-icons-team|11.8.0|
|vscode-import-cost|wix|2.15.0|
|vscode-language-babel|mgmcdermott|0.0.35|
|vscode-npm-script|eg2|0.3.23|
|vscode-simple-icons|LaurentTreguier|1.16.0|
|vscode-svgviewer|cssho|2.0.0|
|vscode-tailwindcss|bradlc|0.7.4|
|vscode-todo-highlight|wayou|1.0.5|
|vscode-yaml|redhat|1.2.2|
|vscodeintellicode|VisualStudioExptTeam|1.2.15|
|xd|adobe|1.2.3|
</details>

Extension Logs
-----

> Find this from the first few lines of the relevant Output pane:
View -> Output -> 'HashiCorp Terraform'

**Comment by radeksimko** [comment] 2022-01-04 12:20
Hi @KhimairaCrypto 
It is unfortunately hard to tell what the cause of the problem may be.

Do you mind sharing the logs, as instructed near the bottom of the issue template?

> Find this from the first few lines of the relevant Output pane:
> View -> Output -> 'HashiCorp Terraform'

Thanks.

**Comment by KhimairaCrypto** [comment] 2022-01-12 01:00
Seems like the last terraform and VS code updates fixed the issue. Fingers cross that is not going to brake ever again ;-)

**Comment by radeksimko** [comment] 2022-01-12 08:09
Thanks, I'm going to close the issue for now.

Do let us know if the problem comes back.

**Closed by radeksimko** 2022-01-12 08:09 UTC
Labels: question, waiting-response
