### ISSUE TITLE
Syntax Highlighting for Successive Interpolated Values Incorrect

### ISSUE THREAD

**Issue by NJITman** [hashicorp/vscode-terraform#1118] opened 2022-05-26 02:46 UTC
### Extension
v2.22.0

### VS Code
1.67.2 (system setup)

### Operating System
Windows 10 21H2

### Terraform Version
1.1.8

### Steps To Reproduce

When creating a string using interpolation, if two interpolated values are placed one after the other with no intervening characters, TF VSC extension shows second interpolation as being text.  It does not generate a plan error, so it is acceptable to use in TF and generates the proper results.  However, the TF linter is showing the second interpolation as text when it should show it as an interpolated value.

In the example below, compare the highlighting of **bucket_name** (has intervening period between two interpolated values) and **aliases** (does not have any intervening characters).

![Image 002](https://user-images.githubusercontent.com/10375636/170404505-d1a3857c-5979-4425-975d-ab61c2f803f5.jpg)

### Expected Behavior
All interpolated values should be displayed with proper syntax highlighting.

### Actual Behavior
If two interpolated values are placed one after the other, the first interpolated value is shown with correct highlighting, while the second is shown with text highlighting.

**Comment by radeksimko** [comment] 2022-05-26 07:23
Hi @NJITman 
I can verify this is duplicate of https://github.com/hashicorp/vscode-terraform/issues/1040 which was addressed by https://github.com/hashicorp/syntax/pull/34 / https://github.com/hashicorp/vscode-terraform/pull/1114.

It will be part of the next release `v2.23.0`.

![Screenshot 2022-05-26 at 08 20 43](https://user-images.githubusercontent.com/287584/170438838-d3a5e1a0-b8a9-4be3-84f8-b4c0cdd368df.png)

**Closed by radeksimko** 2022-05-26 07:23 UTC
Labels: bug
