### ISSUE TITLE
Broken highlighting with curly brackets

### ISSUE THREAD

**Issue by queglay** [hashicorp/vscode-terraform#470] opened 2020-08-23 00:49 UTC
<img width="984" alt="Screen Shot 2020-08-23 at 10 16 02 am" src="https://user-images.githubusercontent.com/4046493/90968318-11e79c00-e52a-11ea-9c26-f4490e88e01e.png">

You can see here below 'id' which should be a string, the highlighting persists as a string for the rest of the document.

**Comment by joshsleeper** [comment] 2020-08-23 19:13
I think this is a duplicate of #466 ?

**Comment by DenWin** [comment] 2020-08-24 11:54
> I think this is a duplicate of #466 ?

Yes it is! Remove the equal sign after "query" and the highlighting would work instantly - though breaking the code.

**Comment by patoroco** [comment] 2020-08-25 07:19
Hi, I've had the same issue, and as pointed @queglay, downgrading to 2.1.1 fixed the issue (in my case because using `/*` as a suffix in the ARN).

The steps that I followed to downgrade (I followed [this guide](https://tpodolak.com/blog/2017/04/09/downgrading-visual-studio-code-extension)):
1. Download the 2.1.1 manually  (click on the link) https://hashicorp.gallery.vsassets.io/_apis/public/gallery/publisher/hashicorp/extension/terraform/2.1.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
2. Rename the file to use the file extension `VSIX` only (without `Package`).
3. In VS Code, open the Command Menu (`Cmd` + `Shift` + `P` on Mac OS X), and search for `Install from VSIX` and select the file that was downloaded/renamed.


I hope that this helps someone :)

**Comment by ruankr** [comment] 2020-08-25 07:22
It's a lot easier to just use the built in feature to install previous versions. Simply go to the plugin manager in VS Code, search the plugin, click the cog icon and select "Install another version"
![image](https://user-images.githubusercontent.com/63055439/91144526-10de7800-e6ac-11ea-916f-0db884151f29.png)

**Comment by patoroco** [comment] 2020-08-25 07:36
Oh, thanks @ruankr!

I didn't know about this way (actually, it was the first time I needed to install a non-the-last version), but this is pretty easier!

**Comment by paultyng** [comment] 2020-08-25 17:43
I think this is the same as #466, going to merge them together. We are currently investigating the syntax issues and plan to publish a hotfix once resolved.

**Closed by paultyng** 2020-08-25 17:43 UTC
Labels: bug, syntax
