### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by yosefbennywidyo** [hashicorp/vscode-terraform#465] opened 2020-08-20 01:42 UTC
- Issue Type: `Performance`
- Extension Name: `terraform`
- Extension Version: `2.1.1`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.48.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/yosef_bw/hashicorp.terraform-unresponsive.cpuprofile.txt`
[hashicorp.terraform-unresponsive.cpuprofile.txt](https://github.com/hashicorp/vscode-terraform/files/5100173/hashicorp.terraform-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by radeksimko** [comment] 2020-08-25 10:49
Hi @yosefbennywidyo
I admit this is the first time I see a CPU profile for a VS Code extension, but I can't see anything unusual.

More importantly it's far more likely that CPU spikes would be caused by the language server as it does much more work with regards to parsing the configuration, discovering files on disk etc.

With that in mind I would suggest following https://github.com/hashicorp/terraform-ls/blob/master/docs/TROUBLESHOOTING.md#cpu-profiling -> do you mind collecting CPU profile for the server and confirming that this still happens with the latest version of the language server (0.6.1 at the time of writing)?

**Comment by yosefbennywidyo** [comment] 2020-08-26 05:44
I found this files:

1. `tmp/terraform-ls-76668.log`

```
2020/08/26 13:38:59 serve_command.go:101: Terraform executions will be logged to /tmp/tf-exec-{{lsPid}}-{{args}}.log (interpolated at the time of execution)
2020/08/26 13:38:59 serve_command.go:137: Starting terraform-ls 0.6.1
2020/08/26 13:38:59 service.go:60: Preparing new session ...
2020/08/26 13:38:59 service.go:77: Worker pool size set to 12
2020/08/26 13:38:59 watcher.go:118: watching for changes ...
2020/08/26 13:38:59 langserver.go:69: Starting server (pid 76668) ...
2020/08/26 13:39:08 server.go:502: Server signaled to stop with err=missing required content-length
2020/08/26 13:39:08 server.go:145: Reading next request: missing required content-length
2020/08/26 13:39:08 service.go:256: session stopped unexpectedly (err: missing required content-length)
2020/08/26 13:39:08 service.go:265: stopping walker for session ...
2020/08/26 13:39:08 service.go:267: walker stopped
2020/08/26 13:39:08 service.go:271: stopping watcher for session ...
2020/08/26 13:39:08 service.go:276: watcher stopped
2020/08/26 13:39:08 service.go:281: cancelling any root module loading ...
2020/08/26 13:39:08 service.go:283: root module loading cancelled
2020/08/26 13:39:08 langserver.go:81: Stopping server (pid 76668) ...
2020/08/26 13:39:08 langserver.go:85: Server (pid 76668) stopped.
```

2. `tmp/terraform-ls-cpu.prof` - it's empty

**Comment by radeksimko** [comment] 2020-08-26 06:11
Thank you for sharing the log.

It appears that 9 seconds after starting the server the client sends malformed request to it (without `content-length`) for some reason. 🤔 

1. Are there any more log files in `tmp`? i.e. did the client attempt to start the server again?
2. Does the CPU spike just during the 9 seconds while the server is up, or also afterwards?
3. Perhaps obvious, but I'll ask anyway - Can you just confirm (by checking the Activity Monitor in MacOS & sorting the list by `% CPU`) that it's a VSCode process consuming the excessive CPU and _not_ `terraform-ls` or any other process?

**Comment by yosefbennywidyo** [comment] 2020-08-26 11:46
After I opened this issue, I never had the problem again. I'll let you know when it's happen again and add the Activity Monitor sorted by `% CPU`.

Thank you @radeksimko for your response.

**Comment by radeksimko** [comment] 2020-08-28 16:40
I'm going to close this issue for now as I wasn't able to reproduce it, but do let us know if it occurs again.

**Closed by radeksimko** 2020-08-28 16:41 UTC
Labels: bug
