### ISSUE TITLE
Terraform cloud workspace created during initialization of extension

### ISSUE THREAD

**Issue by zotoMIT** [hashicorp/vscode-terraform#1052] opened 2022-04-14 18:20 UTC
## Versions

This bug is reproducible in:
 - [ ] the **latest** version of the extension (below)
 - [ ] the **latest** version of the language server (below)

### Extension

```
v2.21.0
```

### Language Server

```
vscode/extensions/hashicorp.terraform-2.21.0-darwin-arm64/bin/terraform-ls version 
0.26.0
platform: darwin/arm64
go: go1.17.7
compiler: gc

```

### VS Code

```
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:47:29.396Z (3 days ago)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.4.0
```

### Operating System

```
Mac OS 12.3.1 21E258
```

### Terraform Version

```
Terraform v1.1.7
on darwin_arm64
```

### Steps To Reproduce

This issue may not be with the extension itself, but I'm trying to understand what command is being run by the extension that causes the underlying issue.  The issue is that after deleting a workspace from terraform cloud, starting vscode with the extension enabled causes the extensions initialization process(*i'm assuming) to see a directory with a deleted terraform cloud workspace, and create it again.  

1. Login to terraform cloud via CLI
2. start a project/folder with some terraform code, in your main block, use the "cloud" block. 
```
cloud {
    organization = "My org" ...
```
3. delete the workspace from terraform cloud via console.  
- At this point, a `terraform plan, init, show, etc` doesn't result in a new workspace being created without interaction.
4. restart vscode, the extension will recreate the workspace.

### Expected Behavior
Old workspaces are not re-created on start.

### Actual Behavior
The extension re-creates the workspace
 
### Additional context
Here is the log from the extension, showing the creation of the workspace. 
```
2022-04-14T11:05:53.627-0400 [INFO]  CLI command args: []string{"providers", "schema", "-json", "-no-color"}
2022-04-14T11:05:53.627-0400 [DEBUG] Using modified User-Agent: Terraform/1.1.7 HashiCorp-terraform-exec/0.16.0
2022-04-14T11:05:53.627-0400 [DEBUG] Using modified User-Agent: HashiCorp Terraform/1.1.7 (+https://www.terraform.io) HashiCorp-terraform-exec/0.16.0
2022-04-14T11:05:53.630-0400 [TRACE] Meta.Backend: BackendOpts.Config not set, so using settings loaded from :0,0-0
2022-04-14T11:05:53.630-0400 [TRACE] Meta.Backend: built configuration for "cloud" backend with hash value 3158543664
2022-04-14T11:05:53.631-0400 [TRACE] Preserving existing state lineage "xxxxxxx-8f17-e646-e362-xxxxxxxxx"
2022-04-14T11:05:53.631-0400 [TRACE] Preserving existing state lineage "xxxxxxx-8f17-e646-e362-xxxxxxxxx"
2022-04-14T11:05:53.631-0400 [TRACE] Meta.Backend: working directory was previously initialized for "cloud" backend
2022-04-14T11:05:53.631-0400 [TRACE] Meta.Backend: using already-initialized, unchanged "cloud" backend configuration
2022-04-14T11:05:53.631-0400 [DEBUG] Service discovery for app.terraform.io at https://app.terraform.io/.well-known/terraform.json
2022-04-14T11:05:53.631-0400 [TRACE] HTTP client GET request to https://app.terraform.io/.well-known/terraform.json
2022-04-14T11:05:54.053-0400 [TRACE] Meta.Backend: instantiated backend of type *cloud.Cloud
2022-04-14T11:05:54.055-0400 [TRACE] providercache.fillMetaCache: scanning directory .terraform/providers
2022-04-14T11:05:54.056-0400 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/hashicorp/aws v3.74.3 for darwin_arm64 at .terraform/providers/registry.terraform.io/hashicorp/aws/3.74.3/darwin_arm64
2022-04-14T11:05:54.056-0400 [TRACE] providercache.fillMetaCache: including .terraform/providers/registry.terraform.io/hashicorp/aws/3.74.3/darwin_arm64 as a candidate package for registry.terraform.io/hashicorp/aws 3.74.3
2022-04-14T11:05:54.249-0400 [DEBUG] checking for provisioner in "."
2022-04-14T11:05:54.249-0400 [DEBUG] checking for provisioner in "/opt/homebrew/bin"
2022-04-14T11:05:54.249-0400 [TRACE] Meta.Backend: backend *cloud.Cloud supports operations
2022-04-14T11:05:54.250-0400 [TRACE] cloud: requesting state manager for workspace "test-workspace"
2022-04-14T11:05:54.294-0400 [TRACE] cloud: Creating Terraform Cloud workspace MyORG/test-workspace
2022-04-14T11:05:54.992-0400 [TRACE] cloud: requesting state lock for workspace "test-workspace"
2022-04-14T11:05:54.992-0400 [TRACE] cloud: reading remote state for workspace "test-workspace"
2022-04-14T11:05:55.039-0400 [TRACE] cloud: retrieving remote state snapshot for workspace "test-workspace"
2022-04-14T11:05:55.039-0400 [TRACE] cloud: loading configuration for the current working directory
2022-04-14T11:05:55.039-0400 [TRACE] cloud: loading configuration for the current working directory
2022-04-14T11:05:55.058-0400 [TRACE] terraform.NewContext: starting
2022-04-14T11:05:55.058-0400 [TRACE] terraform.NewContext: complete
2022-04-14T11:05:55.058-0400 [TRACE] cloud: finished building terraform.Context
2022-04-14T11:05:55.058-0400 [TRACE] LoadSchemas: retrieving schema for provider type "registry.terraform.io/hashicorp/aws"
2022-04-14T11:05:55.058-0400 [TRACE] terraform.contextPlugins: Initializing provider "registry.terraform.io/hashicorp/aws" to read its schema
2022-04-14T11:05:55.058-0400 [DEBUG] created provider logger: level=trace
```

I have noticed through trial and error that the workspace is created with the name that exists in .terraform/environment
So an easy way to see it create new workspace is to modify the contents of this file with a new/nonexisting workspace.  Doing so will cause a new workspace to be created on a restart of VScode.  

I have noticed that removing the .terraform folder entirely stops the issue from happening.  

Ideally i would like the plugin to not attempt to create new workspaces in tf cloud, further, i would like to understand what command its running that is causing this.

**Comment by radeksimko** [comment] 2022-04-20 11:48
Hi @zotoMIT 
I tried reproducing what you described but my experience differed, specifically you mentioned

> delete the workspace from terraform cloud via console.
> At this point, a terraform plan, init, show, etc doesn't result in a new workspace being created without interaction.

I used the following config
```hcl
terraform {
  cloud {
    organization = "radeksimko"
    workspaces {
      name = "my-app-prod"
    }
  }
}
```

and the `my-app-prod` workspace was re-created automatically when I ran `terraform init`.

This aligns with the documentation published at https://www.terraform.io/language/settings/backends/remote

> If previous state is present when you run terraform init and the corresponding remote workspaces are empty or absent, Terraform will create workspaces and/or update the remote state accordingly.

--- 

The extension does _not_ run `terraform init` by itself, although it allows you to do so via the command palette.
![Screenshot 2022-04-20 at 12 41 49](https://user-images.githubusercontent.com/287584/164222884-612609b0-39eb-4ed8-a111-94884cb440fb.png)

The only commands we run on the background are the following:

 - `terraform version -json`
 - `terraform providers schema -json`

each of which enables richer and accurate completion, hover etc. tailored to the version of Terraform and any providers in use.

--- 

I'm going to close this issue as I cannot reproduce it and even if I could it would most likely be related to TF Core, where I'd recommend filing such an issue, if it differs from expectations and/or documented behaviours https://github.com/hashicorp/terraform/issues/new/choose

**Closed by radeksimko** 2022-04-20 11:48 UTC
Labels: question
