### ISSUE TITLE
azurerm_container_group.container.cpu is reported as a number but all sample documentation shows it as a string

### ISSUE THREAD

**Issue by aaronswainonset** [hashicorp/vscode-terraform#830] opened 2021-11-01 06:02 UTC
## Versions

This bug is reproducible in:
 - [x] the **latest** version of the extension (below)
 - [x] the **latest** version of the language server (below)

### Extension

```
v2.16.0
```

### Language Server

```
0.23.0
```

### VS Code

```
1.61.2
```

### Operating System

```
Windows 10 20H2
```

### Steps To Reproduce
Create a azurerm_container_group resource with a container block as shown below. Hover the cursor over "cpu" or "memory" to see the intellicode description - they're both specified as 'number' data types.

```
resource "azurerm_container_group" "container" {
  container {
    cpu    = ""
    memory = ""
  }
}
```

### Expected Behavior
The Terraform documentation includes samples that show "cpu" and "memory" being assigned string values. The intellicode pop up should say they're 'string' data type.

### Actual Behavior
They're both identified as 'number' data types.

**Comment by radeksimko** [comment] 2021-11-01 11:55
Hi @aaronswainonset 
The intellisense is actually correct. Both attributes are expected to be numbers, which can be also verified from the codified schema here:

https://github.com/hashicorp/terraform-provider-azurerm/blob/b0c897055329438be6a3a159f6ffac4e1ce958f2/internal/services/containers/container_group_resource.go#L228-L238

Generally speaking the data you see in intellisense - in completion, hover or elsewhere, come from type constraints as defined by the provider itself, not by what you have in the config.

Terraform allows certain types to be converted to others, but we recommend types to align whenever possible as it also aids configuration readability.

I am going to close this issue as there this works as intended, but do let us know if you run into any other unexpected behaviours or issues!

**Closed by radeksimko** 2021-11-01 11:55 UTC
Labels: question

**Comment by aaronswainonset** [comment] 2021-11-01 12:05
Hi @radeksimko . Thanks for your comments. I suppose the issue lies with Terraform's documentation/samples so I'll raise an issue there.
