### ISSUE TITLE
Format does not align = signs when type is multiline array

### ISSUE THREAD

**Issue by Joren-Thijs** [hashicorp/vscode-terraform#1700] opened 2024-02-28 18:56 UTC
### Extension Version

v2.29.4

### VS Code Version

Version: 1.86.2 (Universal)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:42:13.651Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0

### Operating System

macOs Sonoma 14.3

### Terraform Version

Terraform v1.7.4 on darwin_arm64 + provider registry.terraform.io/hashicorp/azurerm v3.64.0 + provider registry.terraform.io/hashicorp/random v3.6.0

### Steps to Reproduce

take a simple formatting example like this

before
```tf
resource "azurerm_key_vault_secret" "sa_connectionstring" {
  name         = "storage-account-connectionstring"
  value        = azurerm_storage_account.main.primary_connection_string
  key_vault_id = azurerm_key_vault.main.id
  depends_on        = [
    azurerm_key_vault_access_policy.current
  ]
}
```

### Expected Behavior

What i expect and want is for depends_on's '=' sign to be vertically aligned with the others
```tf
resource "azurerm_key_vault_secret" "sa_connectionstring" {
  name         = "storage-account-connectionstring"
  value        = azurerm_storage_account.main.primary_connection_string
  key_vault_id = azurerm_key_vault.main.id
  depends_on   = [
    azurerm_key_vault_access_policy.current
  ]
}
```

### Actual Behavior

when i format this document (format on save is turned on, but manual formatting gives same result). Terraform collapses the whitespace but does not vertically align the = sign of the depends_on parameter
```tf
resource "azurerm_key_vault_secret" "sa_connectionstring" {
  name         = "storage-account-connectionstring"
  value        = azurerm_storage_account.main.primary_connection_string
  key_vault_id = azurerm_key_vault.main.id
  depends_on = [
    azurerm_key_vault_access_policy.current
  ]
}
```

If i write the array differently to make it single line. the issue does not reproduce. However this is not a solution because currently the extension is causing whitespace changes for my coworker who uses windows and doesn't have this problem.
```tf
resource "azurerm_key_vault_secret" "sa_connectionstring" {
  name         = "storage-account-connectionstring"
  value        = azurerm_storage_account.main.primary_connection_string
  key_vault_id = azurerm_key_vault.main.id
  depends_on   = [azurerm_key_vault_access_policy.current]
}
```

### Project Structure

```sh
Kubernetes
│   ├── cert-manager-values.yml
│   ├── cert-manager.tf
│   ├── kaspar-services-namespace.tf
│   ├── linkerd-cert.tf
│   ├── linkerd-values-ha.yaml
│   ├── linkerd-values.yaml
│   ├── linkerd-viz-values.yml
│   ├── linkerd-viz.tf
│   ├── linkerd.tf
│   ├── main.tf
│   ├── nginxinc-ingress-values.yml
│   ├── nginxinc-ingress.tf
│   └── variables.tf
├── Main
│   ├── README.md
│   ├── aks-cluster.tf
│   ├── azure-sql.tf
│   ├── dns.tf
│   ├── key-vault.tf
│   ├── main.tf
│   ├── networking.tf
│   ├── outputs.tf
│   ├── security-internal.tf
│   ├── security.tf
│   ├── storage.tf
│   ├── terraform.tfvars
│   └── variables.tf
└── modules
    ├── aks-module
    │   └── variables.tf
    └── common-module
        ├── main.tf
        ├── outputs.tf
        └── variables.tf
```

### Anything Else?

I also tried disabeling my other vscode extensions and emptying my settitngs.json file so it only contained settings for terraform. But this did not fix the issue.
```json
{
  "[terraform]": {
    "editor.defaultFormatter": "hashicorp.terraform",
    "editor.formatOnSave": true,
    "editor.formatOnSaveMode": "file"
  },
  "[terraform-vars]": {
    "editor.defaultFormatter": "hashicorp.terraform",
    "editor.formatOnSave": true,
    "editor.formatOnSaveMode": "file"
  }
}
```

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment] 2024-03-01 09:59
Hi @Joren-Thijs, thanks for the report. I can reproduce the problem.

The language server uses `terraform fmt` to format the configuration files. When I run `terraform fmt` from the command line, I get the same behavior as you see. However, I don't think there is anything we can do on the extension or language server side, as this seems to be a Terraform issue.

Would you mind raising the issue at https://github.com/hashicorp/terraform? Be sure to include your excellent examples.

I'll close this for now, but please let me know if you run into any other issues.

**Closed by dbanck** 2024-03-01 09:59 UTC
Labels: bug
