### ISSUE TITLE
Equality being treated as assignment

### ISSUE THREAD

**Issue by acdifran** [hashicorp/vscode-terraform#320] opened 2020-05-22 01:08 UTC
I wanted to set my established variables to be a different color than the left-hand assignments. After changing syntax highlighting for this I noticed existing variables were being colored as "assignments" if I was comparing them to something with "==". I looked through the grammar rules and made a small adjustment to add a lookahead rule for "==" to prevent preceding variables from being recognized as "assignment". 

The relevant piece of code starts on line 115 of terraform.json:

```json
    {
      "captures": {
        "1": {
          "name": "variable.other.assignment.terraform"
        },
        "2": {
          "name": "keyword.operator.terraform"
        }
      },
      "comment": "Value assignments (left hand side not in double quotes)",
      "match": "([\\w_-]+)\\s*(=(?!=))\\s*"
    },
    {
      "captures": {
        "1": {
          "name": "punctuation.quote.double.terraform"
        },
        "2": {
          "name": "variable.assignment.terraform"
        },
        "3": {
          "name": "punctuation.quote.double.terraform"
        },
        "4": {
          "name": "keyword.operator.terraform"
        }
      },
      "comment": "Value assignments (left hand side in double quotes)",
      "match": "(\")([\\w_-]+)(\")\\s*(=(?!=))\\s*"
    },
```

I added "(?!=)" within the "(=)" group in both matches to check for "==".

Below are screenshots with the old rules and then a screenshot with the rule change.

Old Rules:

Correctly shows "variable.other.terraform" when there is no "=" present:
<img width="842" alt="Screen Shot 2020-05-21 at 5 51 15 PM" src="https://user-images.githubusercontent.com/25591626/82620416-3f205900-9b8d-11ea-9b1b-5db3779dea47.png">

Incorrectly shows "variable.other.assignment.terraform" when using the "==" operator:
<img width="740" alt="Screen Shot 2020-05-21 at 5 51 23 PM" src="https://user-images.githubusercontent.com/25591626/82620420-421b4980-9b8d-11ea-8cd6-2ece80f51089.png">

New Rules:

Correctly shows "variable.other.terraform" when using the "==" operator:
<img width="826" alt="Screen Shot 2020-05-21 at 5 52 29 PM" src="https://user-images.githubusercontent.com/25591626/82620424-434c7680-9b8d-11ea-8857-2d5bed644160.png">

**Comment by dbanck** [comment] 2022-02-01 15:55
The current version of the extension detects and highlights comparisons correctly. I'm not able to reproduce this issue.

<img width="632" alt="CleanShot 2022-02-01 at 16 49 42@2x" src="https://user-images.githubusercontent.com/45985/152002096-91020737-0627-4193-ac61-922212dec8fc.png">

I'm going to close this for now, but if this is still an issue please respond and we'll re-open.

**Closed by dbanck** 2022-02-01 15:55 UTC
Labels: syntax, needs-reproduction
