### ISSUE TITLE
Usage `references` still not exist for tf >= 0.12 

### ISSUE THREAD

**Issue by MaxymVlasov** [hashicorp/vscode-terraform#520] opened 2020-11-23 12:07 UTC
Hi
One of the major features of v1.x extention was codelens - references to `resource`, `variable` etc.

![](http://i.piccy.info/i9/2edf2d7d9457b0261049477725625376/1606132602/96594/1406638/Screenshot_from_2020_11_23_13_56_21.png)

Please, return it, because without it very hard to work with Terraform in VS Code.

**Comment by Breighton** [comment] 2020-12-09 20:30
Yes, please return this very valuable feature!!!

**Comment by paultyng** [comment] 2020-12-16 19:40
Think this is a duplicate of https://github.com/hashicorp/terraform-ls/issues/169, going to merge it to that issue.

**Closed by paultyng** 2020-12-16 19:40 UTC
Labels: codelens
