### ISSUE TITLE
VS Code uses 250% CPU when it discovered an "error" (works in version of provider, does not work in the later version of provider).

### ISSUE THREAD

**Issue by periwinkleFTW** [hashicorp/vscode-terraform#1824] opened 2024-08-19 22:15 UTC
### Extension Version

v2.32.2

### VS Code Version

Version: 1.92.1 (Universal)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin x64 23.5.0

### Operating System

macOS Sonoma 14.5

### Terraform Version

Terraform v1.5.0

### Behavior

Opening a file that contains definitions that do not work between versions cause VS Code to hog too many resources

### Steps to Reproduce

resource "google_secret_manager_secret" "ingestion_service_account_key_secret" {
  secret_id = "account-key-83t53gj"
  project   = var.project
  replication {
    automatic = true
  }
}

### Terraform Configuration

```terraform
# This configuration works in tf 1.5.0 but for some reason terraform extension freaks out

resource "google_secret_manager_secret" "ingestion_service_account_key_secret" {
  secret_id = "account-key-83t53gj"
  project   = var.project
  replication {
    automatic = true
  }
}
```

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by raelga** [comment] 2024-10-17 15:27
Were you able to resolve the issue?

**Comment by periwinkleFTW** [comment] 2024-10-17 16:08
> Were you able to resolve the issue?

No, i just do what I have to do as fast as I can. Close the file tab that has an issue and restart VS Code

**Comment by dbanck** [comment] 2024-10-17 16:18
Hi @periwinkleFTW, thanks for raising this issue.

Can you share more details about your project structure? At the moment I can't reproduce the high CPU with the `google_secret_manager_secret` snippet. What version of the provider are you using? 
Can you reproduce the behaviour you're seeing in a smaller, shareable project?

**Comment by periwinkleFTW** [comment] 2024-10-17 17:58
> Hi @periwinkleFTW, thanks for raising this issue.
> 
> Can you share more details about your project structure? At the moment I can't reproduce the high CPU with the `google_secret_manager_secret` snippet. What version of the provider are you using? Can you reproduce the behaviour you're seeing in a smaller, shareable project?

Here are the versions:
Terraform v1.9.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.69.1
+ provider registry.terraform.io/hashicorp/google-beta v4.69.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1

I tried replicating this behaviour and i can't anymore. The error indicator is a little annoying but I can live with it

**Comment by dbanck** [comment] 2024-12-04 10:23
If neither of us can reproduce the bug, I'll close this issue for now. If you find any other performance related bugs, please let us know via a new issue.

**Closed by dbanck** 2024-12-04 10:23 UTC
Labels: performance
