### ISSUE TITLE
Proxy provider in module tagged as error

### ISSUE THREAD

**Issue by ZebraFlesh** [hashicorp/vscode-terraform#321] opened 2020-05-22 16:55 UTC
Given a local module that contains a proxy provider definition such as:
```hcl
provider "aws" {
  alias = "target-environment"
}
```
This provider is tagged as an error: `The argument "region" is required, but no definition was found.` Since this is [what the docs tell you to do](https://www.terraform.io/docs/configuration/modules.html#passing-providers-explicitly) it seems like a bug in the vscode extension.

**Comment by apparentlymart** [comment] 2020-06-05 01:17
I suspect this is related to -- or possibly entirely caused by -- hashicorp/terraform#21408.

**Comment by paultyng** [comment] 2020-06-05 01:21
This issue predates are most recent release ([v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1)) so its probably worth testing it again. Notably, `validate` is not something the extension will perform any longer, as that functionality is being delegated to the language server.

**Comment by radeksimko** [comment] 2020-06-05 08:41
Also this issue tracks the validation functionality on the language server side: https://github.com/hashicorp/terraform-ls/issues/27

**Comment by radeksimko** [comment] 2022-05-27 14:41
I cannot reproduce this problem anymore which may be in part because the v2 extension does not perform validation in the same way. It only does a minimal validation of HCL. We plan to introduce some schema-based validation as part of https://github.com/hashicorp/vscode-terraform/issues/720

With that in mind Im going to close this issue.

**Closed by radeksimko** 2022-05-27 14:41 UTC
Labels: diagnostics, needs-reproduction
