### ISSUE TITLE
Azure Terraform devcontainer has incorrect settings causing terraform-ls to fail to start

### ISSUE THREAD

**Issue by MrLuje** [hashicorp/vscode-terraform#1220] opened 2022-08-31 08:10 UTC
### Extension

```
v2.24.1
```

### VS Code

```
Version: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z (2 wks ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044
```

### Operating System

```
Windows 10 - 21H2 - 19044.1766
WSL2 - Linux HVS-PF346A2W 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Terraform Version

```
v1.2.8
```

### Steps To Reproduce

1. Add a remote container with ubuntu and latest terraform, ex :
devcontainer.json
```json
{
	"name": "Ubuntu",
	"build": {
		"dockerfile": "Dockerfile",
		"args": { "VARIANT": "ubuntu-22.04" }
	},
	"remoteUser": "vscode",
	"features": {
		"terraform": "latest"
	}
}
```
Dockerfile
```dockerfile
ARG VARIANT="jammy"
FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}
```
main.tf
```hcl
terraform {
  required_providers {
    random = {
      source = "hashicorp/random"
      version = "3.4.0"
    }
  }
}

resource "random_id" "server" {
  byte_length = 8
}
```

### Expected Behavior
Terraform completion should be working inside a remote container

### Actual Behavior
![image](https://user-images.githubusercontent.com/632075/187625176-5157bd4d-7eea-410e-8026-c109bcc8277a.png)
```log
Launching language server: /home/vscode/.vscode-server/extensions/hashicorp.terraform-2.24.1-linux-x64/bin/terraform-ls 
Failure to start terraform-ls. Please check your configuration settings and reload this window
[Error - 8:01:32 AM] Connection to server got closed. Server will not be restarted.
```
 
### Additional context

I don't have any custom settings in vscode for terraform

It was working properly some weeks ago, so I suppose so it is related to a recent release

If I install an older version of the extension (like 2.23), restart vscode, update back to the latest version of the extension, it works fine
But if I recreate the container (command: `Remote-containers: Rebuild container`), I got bacl the same issue so it looks like it fail to work from a fresh container

**Comment by jpogran** [comment] 2022-08-31 15:54
Hi @MrLuje thanks for the report! This was an interesting problem to figure out. 

You are correct, you aren't providing any custom extension settings, the [container you're using is](https://github.com/microsoft/vscode-dev-containers/blob/c0dcc9e14fae2498ad8e7ec8e5d21a1c8b72a079/containers/azure-terraform/.devcontainer/devcontainer.json#L29-L35). We did change some setting names in our extension with the 2.24.0 release, but we still honor the old names so this should not be happening. The problem is that they are providing an empty `args` which means terraform-ls doesn't start and serve. I'll put up a PR in their repo with modifications and see if we can get the source adjusted.

In the mean time, adjust your `.devcontainer.json` like this and rebuild your container:

```
{
	"name": "Ubuntu",
	"build": {
		"dockerfile": "Dockerfile",
		"args": { "VARIANT": "ubuntu-22.04" }
	},
	"remoteUser": "vscode",
	"features": {
		"terraform": "latest"
	},
	"settings": {
		"terraform.languageServer.enable": true,
		"terraform.languageServer.args": [
			"serve"
		]
	}
}
```

The new settings will override the container's defaults and the extension should load correctly.

**Comment by MrLuje** [comment] 2022-08-31 18:33
Thanks for the quick analysis :)

**Comment by jpogran** [comment] 2022-09-06 17:18
I've updated the target for these devcontainers in https://github.com/devcontainers/features/pull/131, so future releases shouldn't use the incorrect setting values. 

With the root cause fixed and a workaround present, I'm going to close this issue. Please let us know if this happens again.

**Closed by jpogran** 2022-09-06 17:18 UTC
Labels: bug
