### ISSUE TITLE
Terraform language server won't start

### ISSUE THREAD

**Issue by alexhollis** [hashicorp/vscode-terraform#1213] opened 2022-08-24 00:33 UTC
Issue Description
=====

Terraform language server won't start

Environment Information
=====

Terraform Information
-----

Version:	1.2.7
Platform:	darwin_amd64
Outdated:	false
    

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Darwin x64 21.6.0 |
| VSCode | 1.70.2|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|cloudcode|googlecloudtools|1.20.1|
|code-runner|formulahendry|0.11.8|
|code-spell-checker|streetsidesoftware|2.6.0|
|githistory|donjayamanne|0.6.19|
|gitlens|eamodio|12.1.2|
|go|golang|0.35.2|
|makefile-tools|ms-vscode|0.5.0|
|remote-containers|ms-vscode-remote|0.245.2|
|remote-ssh|ms-vscode-remote|0.84.0|
|remote-ssh-edit|ms-vscode-remote|0.80.0|
|ruby|groksrc|0.1.0|
|ruby|rebornix|0.28.1|
|ruby-rubocop|misogi|0.8.6|
|solargraph|castwide|0.23.0|
|sqltools|mtxr|0.24.0|
|sqltools-driver-pg|mtxr|0.3.0|
|sqltools-driver-sqlite|mtxr|0.3.0|
|terraform|hashicorp|2.24.0|
|theme-dracula-pro|dracula-theme-pro|1.1.0|
|vscode-docker|ms-azuretools|1.22.1|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.3.10|
|vscode-postgresql|ms-ossdata|0.3.0|
|vscode-pull-request-github|GitHub|0.48.1|
|vscode-ruby|wingrunr21|0.28.0|
|vscode-sqlite|alexcvzz|0.14.1|
|vscode-yaml|redhat|1.9.1|
|vscodeintellicode|VisualStudioExptTeam|1.2.23|
</details>

Extension Logs
-----

> Find this from the first few lines of the relevant Output pane:
View -> Output -> 'HashiCorp Terraform'

022/08/23 19:43:43 jobs.go:265: JOBS: Dispatching next job "110151" (scheduler prio: -1, job prio: 0, isDirOpen: false): "OpTypeObtainSchema" for {"file:///Users/alexander.hollis/work/kubernetes-ops/terraform-environments/aws/prod/helm/290-engine-group-47"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13c4898]

goroutine 38 [running]:
github.com/hashicorp/go-version.prereleaseCheck(0xc09a8067e0, 0x3)
	github.com/hashicorp/go-version@v1.6.0/constraint.go:198 +0x18
github.com/hashicorp/go-version.constraintGreaterThanEqual(0xc09a8067e8, 0xc0aa07f858)
	github.com/hashicorp/go-version@v1.6.0/constraint.go:250 +0x25
github.com/hashicorp/go-version.(*Constraint).Check(...)
	github.com/hashicorp/go-version@v1.6.0/constraint.go:163
github.com/hashicorp/go-version.Constraints.Check({0xc0cb192370, 0x1, 0xc}, 0x170c841)
	github.com/hashicorp/go-version@v1.6.0/constraint.go:93 +0x5e
github.com/hashicorp/terraform-ls/internal/state.(*ProviderSchemaStore).schemaExists(0xc0007ed6c0, {{0xc0c90cacfa, 0x6}, {0xc0c90cacf0, 0x9}, {0x1714198, 0x15}}, {0xc0cb192370, 0x1, 0x1})
	github.com/hashicorp/terraform-ls/internal/state/provider_schema.go:227 +0x9c9
github.com/hashicorp/terraform-ls/internal/state.(*ProviderSchemaStore).AllSchemasExist(0xc0008924c0, 0xc0604fc2a7)
	github.com/hashicorp/terraform-ls/internal/state/provider_schema.go:197 +0xef
github.com/hashicorp/terraform-ls/internal/terraform/module.ObtainSchema({0x1d64de0, 0xc053b1f980}, 0x163d6a0, 0xc0bbe71c60, {0xc0604fc2a7, 0x64})
	github.com/hashicorp/terraform-ls/internal/terraform/module/module_ops.go:128 +0xea
github.com/hashicorp/terraform-ls/internal/indexer.(*Indexer).WalkedModule.func8({0x1d64de0, 0xc053b1f950})
	github.com/hashicorp/terraform-ls/internal/indexer/walker.go:135 +0xc5
github.com/hashicorp/terraform-ls/internal/scheduler.(*Scheduler).eval(0xc00088d5c0, {0x1d64d38, 0xc000892500})
	github.com/hashicorp/terraform-ls/internal/scheduler/scheduler.go:70 +0x184
created by github.com/hashicorp/terraform-ls/internal/scheduler.(*Scheduler).Start
	github.com/hashicorp/terraform-ls/internal/scheduler/scheduler.go:48 +0x69
Failure to start terraform-ls. Please check your configuration settings and reload this window
[Error - 7:43:44 PM] Connection to server got closed. Server will not be restarted.
[Error - 7:43:44 PM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (/Users/alexander.hollis/.vscode/extensions/hashicorp.terraform-2.24.0-darwin-x64/out/extension.js:42:4070)
	at Object.dispose (/Users/alexander.hollis/.vscode/extensions/hashicorp.terraform-2.24.0-darwin-x64/out/extension.js:47:9584)
	at _l.handleConnectionClosed (/Users/alexander.hollis/.vscode/extensions/hashicorp.terraform-2.24.0-darwin-x64/out/extension.js:49:9075)
	at _l.handleConnectionClosed (/Users/alexander.hollis/.vscode/extensions/hashicorp.terraform-2.24.0-darwin-x64/out/extension.js:52:12102)
	at r (/Users/alexander.hollis/.vscode/extensions/hashicorp.terraform-2.24.0-darwin-x64/out/extension.js:49:8757)
	at Za.invoke (/Users/alexander.hollis/.vscode/extensions/hashicorp.terraform-2.24.0-darwin-x64/out/extension.js:15:9648)
	at ni.fire (/Users/alexander.hollis/.vscode/extensions/hashicorp.terraform-2.24.0-darwin-x64/out/extension.js:15:10413)
	at pe (/Users/alexander.hollis/.vscode/extensions/hashicorp.terraform-2.24.0-darwin-x64/out/extension.js:16:10887)
	at Za.invoke (/Users/alexander.hollis/.vscode/extensions/hashicorp.terraform-2.24.0-darwin-x64/out/extension.js:15:9648)
	at ni.fire (/Users/alexander.hollis/.vscode/extensions/hashicorp.terraform-2.24.0-darwin-x64/out/extension.js:15:10413)
	at Vo.fireClose (/Users/alexander.hollis/.vscode/extensions/hashicorp.terraform-2.24.0-darwin-x64/out/extension.js:16:523)
	at Socket.<anonymous> (/Users/alexander.hollis/.vscode/extensions/hashicorp.terraform-2.24.0-darwin-x64/out/extension.js:16:1297)
	at Socket.emit (node:events:390:28)
	at Socket.emit (node:domain:475:12)
	at Pipe.<anonymous> (node:net:687:12)

**Comment by jpogran** [comment] 2022-08-24 01:34
Can you please provide some more information about your issue? It's understandable to miss, but we ask you to paste the output logs in the issue template to help us diagnose things.

Is this an upgrade from a previous version? If so, which version?

Do you customize any of the extension settings? If so, can you please post the settings you are using? If this is an upgrade from a previous version, did you use the migration prompt or migrate the settings yourself?

**Comment by alexhollis** [comment] 2022-08-24 03:20
@jpogran  - Sorry about that, logs have been added. 
I updated from v2.23.0
I used the migration prompt for the settings, and the only ones I had customized before were formatting on save: 
`"editor.formatOnSave": true,
    "[terraform]": {
        "editor.defaultFormatter": "hashicorp.terraform",
        "editor.formatOnSave": false,
        "editor.codeActionsOnSave": {
            "source.formatAll.terraform": true
        },
    },
    "[terraform-vars]": {
        "editor.defaultFormatter": "hashicorp.terraform",
        "editor.formatOnSave": false,
        "editor.codeActionsOnSave": {
            "source.formatAll.terraform": true
        },
    },`

**Comment by CheyiLin** [comment] 2022-08-24 06:48
Got exactly the same panic error with the latest `v2.24.0` in a monorepo contains multiple individual modules.

**Comment by dbanck** [comment] 2022-08-24 08:36
Thank you all for reporting this issue!

It seems that the language server panics while obtaining provider schemas. We rely on those schemas to provide auto-completion for resources and data sources of the provider.

I'm trying to reproduce the issue. Can you share more information on your directory structure and what providers and versions you use?

**Comment by dbanck** [comment] 2022-08-24 11:14
If you are affected by this issue, you can [pin the extension version](https://github.com/hashicorp/vscode-terraform#pin-to-a-specific-version-of-the-extension) in VS Code to `v2.23.0` until we release a fix.

That version ships with an older version of the language server (`v0.28.1` instead of `v0.29.0`) which shouldn't panic.

**Comment by alin-grecu** [comment] 2022-08-24 12:41
Same issue, maybe useful hint: opening the individual terraform folders in vscode doesn't crash the language server, but opening in vscode the folder that encompasses all of them (6 repositories) does.

Running on 13' M1 Mac.

**Comment by jpogran** [comment] 2022-08-24 16:36
We've just released 2.24.1 with a fix for this issue to both stable and preview versions. Please let us know how it works for you.

**Comment by CheyiLin** [comment] 2022-08-25 03:09
The `2.24.1` works for me. Thanks!

**Comment by dbanck** [comment] 2022-08-26 10:28
I'm going to close this for now as the issue seems resolved with the latest `2.24.1` release. However, please feel free to create a new issue if you encounter any other bugs.

**Closed by dbanck** 2022-08-26 10:28 UTC
Labels: bug, terraform-ls
