### ISSUE TITLE
Support multiple Terraform folders in a single workspace

### ISSUE THREAD

**Issue by paultyng** [hashicorp/vscode-terraform#330] opened 2020-06-04 20:44 UTC
I have a "workspace" in VSCode that has multiple folders (in this case, one was the LS, and one was a TF config, but also when working on a provider I have the provider Go code and a TF config folder open).

If the TF folder is not the first one listed, the terraform init / working dir provider to the LS is incorrect. I'm not sure if this is an LS bug, a VS Code extension bug, or both?

**Comment by paultyng** [comment] 2020-06-04 20:44
For now I just move my TF folder to the top of the list and it all works ok, so I'm guessing there are just some assumptions somewhere that are incorrect about what folders to pass/use.

**Comment by forstermatth** [comment] 2020-06-04 20:48
This would also be the case for a single-folder workspace that has multiple terraform projects inside it;

```
tf-monorepo/
-- shared_modules/
-- env_one/
-- env_two/
-- env-three/

```

**Comment by paultyng** [comment] 2020-06-04 21:00
@forstermatth in that case, you `init` in each one?

**Comment by forstermatth** [comment] 2020-06-04 21:07
Yep; we have a couple scripts within the repo's package.json right now for commit hooks, which give a good example.

```js
"scripts": {
    ...
    "terraform:validate": "cd ${WORKING_DIR} && terraform init -input=false -backend=false > /dev/null && terraform validate",
    "validate:production": "WORKING_DIR=./terraform/production npm run terraform:validate && echo ✅ validate:production success",
    "validate:staging": "WORKING_DIR=./terraform/staging npm run terraform:validate && echo ✅ validate:staging success",
    "validate:west": "WORKING_DIR=./terraform/west npm run terraform:validate && echo ✅ validate:west success",
    "validate:vault": "WORKING_DIR=./terraform/vault-config npm run terraform:validate && echo ✅ validate:vault success"
}
```

**Comment by smiller171** [comment] 2020-06-04 21:09
@paultyng yes. This is an _extremely_ common pattern with Terraform. All of my repos that aren't just modules to be consumed elsewhere have multiple projects in a single repo. We use Atlantis to manage it, or cd into the project we're working with at that time.

The language server started by @juliosueiras https://github.com/juliosueiras/terraform-lsp didn't have these problems at all

**Comment by paultyng** [comment] 2020-06-04 21:12
@smiller171 you can change the LS binary you are using to use Julio's (we are also working with him on ours). The terraform-ls project has different limitations than terraform-lsp (you can review them [in the README](https://github.com/hashicorp/terraform-ls#terraform-ls-vs-terraform-lsp) for the ls), as the ways Julio is interacting with Terraform are version specific and not the supported interface for interacting with it.

**Comment by smiller171** [comment] 2020-06-04 21:20
I get that, but the limitations for `terraform-ls` are much more severe right now unfortunately. Not being able to work with multi-project repos is a huge thing, and I can't get it working even in a single project repo.

**Comment by blairham** [comment] 2020-06-04 21:27
I think maybe an option to select which language server to use for this release until those issues are resovled?

**Comment by paultyng** [comment] 2020-06-05 00:20
I wrote up #335 to see if we can add something in the configs or extension prior to release to allow people to more easily choose/install, especially now while the feature sets diverge more.

**Comment by zemanlx** [comment] 2020-06-17 09:01
It may be useful to have it as a VSCode workspace settings where I point where it should expect terraform roots.

These are my usual repo structures with `terraform`:

```
environments/
  lab/
    .terraform/
  live/
    .terraform/
modules/
README.md
```

or when it is project based

```
bin/
src/
test/
terraform/
  .terraform/
README.md
...
```

To be honest I do not have any repo where `.terraform` lives in the repo root. So if I would be able to set where the extension should expect `.terraform` to live it would be awesome! Ideally, for more than one terraform environment.

**Comment by nodakai** [comment] 2020-06-17 10:07
Was it not an option to release a beta version as an extension file (VSIX? I'm not an expert here) which courageous volunteers can manually install before pushing this huge deal-breaker regression to the whole world? _Cf._ https://github.com/microsoft/vscode/issues/15756

**Comment by smiller171** [comment] 2020-06-17 15:21
@nodakai They did, and several of us told them _explicitely_ that this shouldn't be released as-is

**Comment by CallMeLaNN** [comment] 2020-06-22 00:14
I think recent update is a **breaking change** and it was quite rush to switch while the language server is just being developed since Feb without much cover what was available before.

_BTW I've [seen changes in settings](https://github.com/hashicorp/vscode-terraform/issues/341#issuecomment-647176948) that breaks this extension too._

----

> _extremely_ common pattern

Agreed and I got that from experience restructuring project(s) over time.

It will reduce time to refresh a lot of states, different providers version and focus on application specific resources. Just use `terraform_remote_state` to another project for dependency and getting outputs.

Things like VPC, subnets, route tables, some IAM policies and CI/CD is a lot and less frequent to change compare to application infra. Some simple application using lambda + API gateway while other applications using Kubernetes/Helm.

So it is incomplete without this support with or without workspace. Anyway it seems promising after seeing this https://github.com/hashicorp/terraform-ls/pull/167

**Comment by bruceharrison1984** [comment] 2020-06-23 16:41
Same issue. We use a mono-repo structure similar to:
- root
|- app
|- database
|- terraform

This extension is totally broken for us right now

**Comment by trodemaster** [comment] 2020-06-23 18:12
As a workaround you can add a terraform project as the first listed folder in your vscode workspace. That should get you working until the fix is released.

**Comment by paultyng** [comment] 2020-06-24 13:26
Linking this to the relevant tracking issue on the LS: https://github.com/hashicorp/terraform-ls/issues/32

**Comment by radeksimko** [comment] 2020-06-25 17:21
`v0.4.0` was published earlier today. This update should pop up automatically on the next VSCode launch, unless you configured it to point to a custom build.

`v0.4.0` initially supports the following hierarchies https://github.com/hashicorp/terraform-ls/tree/master/internal/terraform/rootmodule/testdata with the caveats that wrong root module may be picked up when there is multiple candidates (see https://github.com/hashicorp/terraform-ls/issues/179 and https://github.com/hashicorp/terraform-ls/issues/180 ) and these root modules have to be `init`d. There is no way of setting custom root modules yet - see https://github.com/hashicorp/vscode-terraform/issues/396

Keep in mind there is also https://github.com/hashicorp/terraform-ls/issues/128 which you may still run into - workaround is mentioned in the thread.

**Closed** 2020-08-18 20:33 UTC
Labels: bug
