### ISSUE TITLE
incorrect highlighting for aws_elasticache_replication_group

### ISSUE THREAD

**Issue by scott-doyland-burrows** [hashicorp/vscode-terraform#1553] opened 2023-08-07 10:43 UTC
### Extension Version

v2.27.1

### VS Code Version

1.79.2

### Operating System

Windows 10 (vscode connecting to Windows Subsystem for Linux)

### Terraform Version

1.5.3

### Steps to Reproduce

Incorrect highlighting:

![image](https://github.com/hashicorp/vscode-terraform/assets/61512176/c114ab12-0d56-4513-a46b-db9bc0173aa8)

Note ```num_cache_clusters``` - also happens with a few other options.

And the ```log_delivery_configuration```.

Also, incorrect in multiple other places, eg:

![image](https://github.com/hashicorp/vscode-terraform/assets/61512176/702a2316-c409-4f07-a889-4e703e56e4fe)

The above code works perfectly, so it is not a code issue.

### Expected Behavior

Colours should be correct.

### Actual Behavior

Colours are incorrect.

### Terraform Configuration

```terraform
resource "aws_elasticache_replication_group" "elasticache" {
  provider = aws.ou

  for_each = var.elasticache

  replication_group_id       = "${local.name}-${each.key}"
  description                = "${local.name}-${each.key}"
  apply_immediately          = each.value.apply_immediately
  at_rest_encryption_enabled = true
  auto_minor_version_upgrade = each.value.auto_minor_version_upgrade
  automatic_failover_enabled = each.value.automatic_failover_enabled
  engine                     = each.value.engine
  engine_version             = each.value.engine_version
  maintenance_window         = each.value.maintenance_window
  multi_az_enabled           = each.value.multi_az_enabled
  node_type                  = each.value.node_type
  num_cache_clusters         = each.value.num_cache_clusters
  parameter_group_name       = each.value.parameter_group_name
  port                       = local.elasticache_port
  transit_encryption_enabled = true
  subnet_group_name          = aws_elasticache_subnet_group.elasticache[each.key].name
  security_group_ids = [
    aws_security_group.elasticache[0].id
  ]

  log_delivery_configuration {
    destination      = aws_cloudwatch_log_group.elasticache_slow_logs[each.key].name
    destination_type = "cloudwatch-logs"
    log_format       = "json"
    log_type         = "slow-log"
  }

  log_delivery_configuration {
    destination      = aws_cloudwatch_log_group.elasticache_engine_logs[each.key].name
    destination_type = "cloudwatch-logs"
    log_format       = "json"
    log_type         = "engine-log"
  }
}

resource "aws_secretsmanager_secret_version" "elasticache" {
  provider = aws.ou

  for_each = var.elasticache

  secret_id = aws_secretsmanager_secret.elasticache[each.key].id
  secret_string = jsonencode(
    {
      elasticache_primary_endpoint = "${aws_elasticache_replication_group.elasticache[each.key].primary_endpoint_address}"
      elasticache_reader_endpoint  = "${aws_elasticache_replication_group.elasticache[each.key].reader_endpoint_address}"
      elasticache_port             = local.elasticache_port
    }
  )
}
```

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by radeksimko** [comment] 2023-08-10 09:41
Hi @scott-doyland-burrows 
There can be a number of different reasons behind the incorrectly highlighted snippets of code.

To find the root cause, would you mind providing the following?

 - `aws` entry in `required_providers` block, so we know the version constraint & provider address
 - (if installed) version of the AWS provider installed (output from `terraform version` contains that)
 - `provider "aws"` block with `ou` alias (whole block isn't needed, just verification it is present in the same module
 - `locals` entry for `elasticache_port`

I am aware that we do not yet recognise the map lookups as per https://github.com/hashicorp/terraform-ls/issues/1225 so that would at least explain all the mis-highlighted lines with `[each.key]`.

**Comment by scott-doyland-burrows** [comment] 2023-08-21 08:32
The incorrect highlighting for ```num_cache_clusters``` seems to have gone away.  I am not sure when...

So, all that remains in the following - I have simplified this so the error is clearer:

![image](https://github.com/hashicorp/vscode-terraform/assets/61512176/857927dc-4f81-4336-85f5-4b27b7d4d2b7)

```
Terraform v1.5.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.13.1
```

vscode terraform extension is ```v2.27.1```

**Comment by radeksimko** [comment] 2023-08-29 13:24
I was able to reproduce this

```hcl
locals {
  elasticache_port = 6379
}

resource "aws_secretsmanager_secret_version" "elasticache" {
  secret_id = "abc"
  secret_string = jsonencode(
    {
      port = local.elasticache_port
    }
  )
}

output "test" {
  value = local.elasticache_port
}
```

![Screenshot 2023-08-29 at 14 20 01](https://github.com/hashicorp/vscode-terraform/assets/287584/6d3da8dd-a90e-4a39-b3fd-17ecbcea968e)

and I believe the main root cause is that since we cannot infer the constraint/type inside of the "literal object", as represented via `{ port = ... }` which then means we avoid any comparison and with the actual reference's type (number) which in turn blocks all the functionality related to the reference, i.e. completion, hover, highlighting or go-to-definition etc.

This is a bug we already track in https://github.com/hashicorp/terraform-ls/issues/1265 so I will close this issue as a duplicate but feel free to subscribe and comment on that issue or let us know if there's any different issue you discover.

**Closed by radeksimko** 2023-08-29 13:24 UTC
Labels: bug, waiting-response
