### ISSUE TITLE
Constant Prompts for AWS SSO Login

### ISSUE THREAD

**Issue by SeanFromIT** [hashicorp/vscode-terraform#1618] opened 2023-11-03 18:01 UTC
### Extension Version

v2.28.2

### VS Code Version

Version: 1.83.1 (Universal)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:46:55.789Z (3 wks ago)
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 22.6.0

### Operating System

macOS Ventura Version macOS 13.6.1 (22G313)

### Terraform Version

Terraform v1.5.5 on darwin_amd64

### Steps to Reproduce

1. Install VS Code
2. Install HashiCorp Terraform extension

### Expected Behavior

If the Terraform extension wants to validate AWS credentials despite no Terraform command being run, it should first prompt the user for permission to do so. If the user does not approve the SSO login, it should not constantly try again.

### Actual Behavior

Despite no Terraform files being open or Terraform commands being run, the extension begins opening AWS SSO login prompts in the user's browser as soon as VS Code is opened. If you do not approve the prompt - and you shouldn't, since there's no indication of where it's coming from - it opens a new prompt. Over and over and over again. Closing VS Code stops the pop-ups. Uninstalling this extension prevents them from reoccurring.

### Anything Else?

This is a fairly vanilla VS Code install with the default Microsoft extensions plus Diff (Fabio Spampinato), Git Blame (Wade Anderson), Git Graph (mhutchie), and HTML CSS Support (ecmel).

Of note, we use a custom AWS CLI credential_process from [https://github.com/synfinatic/aws-sso-cli](https://github.com/synfinatic/aws-sso-cli). Maybe this extension preloads .aws/config and unexpectedly tries to launch the credential_process?

We also have set env var `export AWS_SDK_LOAD_CONFIG=1` so that Terraform uses the AWS config file.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by radeksimko** [comment] 2023-11-06 10:17
Hi @SeanFromIT 
I'm not familiar with the mentioned AWS CLI credential_process but it is most likely this is the cause.

To confirm this theory, can you try to run `terraform version` in any of the directories you tried to open in VS Code? I could imagine the credential wrappers to wrap `terraform` commands in some way and every command to trigger the authentication, although not all commands will ever need authentication.

If you confirm that the auth is triggered by `terraform version` then I would look into whether the tooling can exclude commands which never require auth, e.g. `terraform version` or `terraform fmt`.

In general - as is the case with most VS Code extensions - the extension will not do anything until/unless activated. In this case it can get activated by opening a _folder_ (workspace in VS Code's terms) with matching file extensions, such as `*.tf` or `*.tfvars`. A file does not need to be edited though for the extension to activate.

The extension may also run `terraform providers schema -json` in some circumstances but this should only be triggered after files are open.

**Comment by SeanFromIT** [comment] 2023-11-06 19:48
Confirmed `terraform version` and `terraform fmt` do not trigger the auth prompt.

**Comment by radeksimko** [comment] 2023-11-09 13:04
@SeanFromIT Thanks for the confirmation. Unfortunately I cannot think of a good workaround for you in this case at this point.

It's not wrong for the AWS CLI credential tooling to assume that credentials may be required to run `terraform providers schema -json`. This is because in order for Terraform to know what providers to generate schemas for, it needs to access the state (configuration is only relevant during creation and updates, not deletion) and the state often is stored remotely, hence will often require some form of credentials.

The extension/LS runs the mentioned command to obtain the provider schemas, which then power all features like completion, hover, or diagnostics. It's not the only source of schemas but it is the most accurate one.

The longer-term plan is to host those schemas in the Terraform Registry, such that the extension/LS can reach out to the Registry API on demand and doesn't have to rely on the locally installed providers. We track this in https://github.com/hashicorp/vscode-terraform/issues/737 and https://github.com/hashicorp/terraform-ls/issues/193

There is also https://github.com/hashicorp/terraform-ls/issues/355 which describes another solution to the same problem, but ultimately we'll have to continue utilising multiple different sources as no one solution will work for every user.

We do track one enhancement which could offer a workaround in https://github.com/hashicorp/terraform-ls/issues/645 Disabling the `terraform providers schema -json` command means that you would get either inaccurate or no intelligence related to providers, depending on which providers and which versions you use. If these trade-offs sound acceptable I'd encourage you to upvote that issue and subscribe to it - that helps us prioritise it.

Since I cannot think of any other solutions or workarounds, I will close this issue in favour of the other ones linked above but do let us know if you have alternative suggestions.

**Closed by radeksimko** 2023-11-09 13:04 UTC
Labels: question, waiting-response
