### ISSUE TITLE
Allow controlling aspects of the automatic formatting

### ISSUE THREAD

**Issue by jbg** [hashicorp/vscode-terraform#613] opened 2021-04-25 16:45 UTC
With "format on save" enabled, this extension formats in a way that I find quite unpleasant:

```hcl
resource "aws_ecr_repository" "repo" {
  name                 = "repo"
  image_tag_mutability = "IMMUTABLE"
}
```

I would much prefer this:

```hcl
resource "aws_ecr_repository" "repo" {
  name = "repo"
  image_tag_mutability = "IMMUTABLE"
}
```

Is there any way to adjust this, and if not, could some basic formatting knobs be added?

**Comment by radeksimko** [comment] 2021-04-26 07:25
Hi @jbg 
What you see here is the intended behavior of `terraform fmt`. Specifically, the alignment of equals signs only happens for consecutive runs of single-line arguments. Multi-line arguments are considered to be an entirely separate "group" (with only one item) for alignment purposes, because the benefit of easily scanning over the values doesn't apply when the value itself isn't positioned relative to the equals sign anyway.

As with all of the `terraform fmt` formatting decisions, this is a subjective and therefore essentially arbitrary decision based on tradeoffs made by the original implementer, and it's unlikely to change because that would cause changes for everyone who had previously formatted examples like this with `terraform fmt` in earlier versions. The bar for changes to existing `terraform fmt` layout behaviors is very high, and would typically need to have a strong and objective (rather than subjective) justification to warrant causing diffs for all existing Terraform configurations after upgrading.

**Comment by jbg** [comment] 2021-04-26 07:27
I'm not asking for the default behaviour to change, just for some ability to configure it like most formatting tools offer. The defaults should obviously remain static so as not to suddenly reformat anyone's code.

It sounds like I should be filing this issue on terraform itself though, if this extension is just calling `terraform fmt`.

**Comment by radeksimko** [comment] 2021-04-26 07:37
> It sounds like I should be filing this issue on terraform itself though, if this extension is just calling terraform fmt.

That is correct. Although technically the full chain is `extension -> LS -> Terraform`, i.e.

1. Extension sends `textDocument/formatting` request to LS for a particular file
2. Language server [calls `terraform fmt -`](https://github.com/hashicorp/terraform-ls/blob/6b3f247402b2b7b464fc40e43ed2d61ac3ab9058/internal/langserver/handlers/formatting.go#L49-L52) on the contents of the file
3. Language server responds back to the extension with formatted contents
4. Extension replaces the existing config with the (received) formatted one

 We do not plan to re-implement the formatting outside of Terraform, mostly for the reasons mentioned above (consistency).

**Comment by radeksimko** [comment] 2021-05-05 10:54
As there is no work to be done, I'm going to close this issue.

**Closed by radeksimko** 2021-05-05 10:54 UTC
