### ISSUE TITLE
Invalid syntax highlighting in for loop

### ISSUE THREAD

**Issue by miiitch** [hashicorp/vscode-terraform#407] opened 2020-06-22 14:33 UTC
For this code 
`
 result= = { for pair in setproduct(array1, array1) : "${pair[1]}-${pair[0].id}" => {
    a   = pair[1]
    b = pair[0].name
    }
  }
`

The result is: 
![image](https://user-images.githubusercontent.com/2396269/85299954-3d0c2b80-b4a6-11ea-876d-e877ec2d03d7.png)

The extension version is 2.0

**Comment by DenWin** [comment] 2020-08-24 15:07
This is a duplicate to #466 - or vice versa. Remove the equal sign before the curly bracket - even though breaking the code - the highlighting will be correct.

**Comment by danekan** [comment] 2020-08-24 19:16
```
resource_tags_transformed = {
    for tag, tagvalue in local.resource_tags:
      tag =>  tag == "x-y" ? (length(tagvalue) < 1 ? "${local.tfenv.x}-${local.tfenv.environment}" : tagvalue) : tagvalue
  }
```

breaks both my head a bit but more so the syntax highlighting after ${local.tfenv.environment} and may relate

![image](https://user-images.githubusercontent.com/5197850/91086285-564f6680-e614-11ea-8c31-5bac4ba196ae.png)

**Comment by DenWin** [comment] 2020-08-24 19:28
> ```
> resource_tags_transformed = {
>     for tag, tagvalue in local.resource_tags:
>       tag =>  tag == "x-y" ? (length(tagvalue) < 1 ? "${local.tfenv.x}-${local.tfenv.environment}" : tagvalue) : tagvalue
>   }
> ```
> 
> breaks both my head a bit but more so the syntax highlighting after ${local.tfenv.environment} and may relate
> 
> ![image](https://user-images.githubusercontent.com/5197850/91086285-564f6680-e614-11ea-8c31-5bac4ba196ae.png)

Try removing the equal sign after resource_tags_transformed, this should fix the highlighting, though will break more than your head.

But regarding this bug, I have tried to reproduce this issue in every version starting from 2.0.0.
I can only assume the actual error happend some lines above this one and was potentially similar to #466

**Comment by danekan** [comment] 2020-08-24 19:46
it doesn't happen before this... I can remove this from my code and the syntax highlighting is fine.  and as you point out removing the = sign fixes the interpretation within the very same code block (though, breaks the code itself so isn't helpful to do)

**Comment by DenWin** [comment] 2020-08-24 19:54
My bad, the comment about the reproducing was meant about the bug mentioned in the description.

As for the equal sign. Yes, it will break the code!
But it was never meant as a fix, but as a pointer where the actual problem lies. As well #441 as also #466 do not point to the "= {" a few lines above, but to where the highlighting is broken. If removing the equal sign fixes the highlighting the problem is just there at the equal sign, not any multiline or for loop or even "tags = {". It is just the equal sign before the curly bracket, that needs to be properly identified.

**Comment by aeschright** [comment] 2020-08-25 22:07
The original example is no longer showing that problem as of v2.2.1 so I'm going to close this in order to focus on narrowing down any remaining issues. Please file a new report if there appears to be a regression, or for any other unexpected highlighting results.

**Closed by aeschright** 2020-08-25 22:07 UTC
Labels: bug, syntax
